### ISSUE TITLE
Image hover effect in contact section

### ISSUE THREAD

**Issue by Harshitazz** [itsmohit097/medi-hub#10]
image hover can make the page look less of static.
![Screenshot 2024-05-10 204559](https://github.com/itsmohit097/medi-hub/assets/118474653/c9569955-ec7f-4eda-9327-11a3604e2a44)

**Comment by Tarun2605** [comment]
I am interested in this task please assign this to me. Thanking you in advance.

**Comment by itsmohit097** [comment]
@Harshitazz raised this issue first so i'll assign this to her.
Choose any other which suits the overall theme

**Comment by itsmohit097** [comment]
@Harshitazz 
I removed the contact us section as we don't need this functionality and you also have not updated something . So I'm closing this issue. Raise some new issue. 
Thank you for you valuable time
