### ISSUE TITLE
[Enhancement functionality]: API integration on login and signup

### ISSUE THREAD

**Issue by nagalakshmi08** [itsmohit097/medi-hub#105]
## Description

Hi @itsmohit097 , I want to connect the frontend pages of login and signup forms to the backend server.

## Expected Behavior

Validation of the login/signup details for user authentication. Allowing users to access the website only if they have an valid account. 

## Steps to Reproduce (if applicable)

1.Taking input from user.
2.Checking the data in database.
3.Successful login/signup if valid data is entered.

Please assign me this task , I want to contribute to this project under GSSoC'24.

**Comment by itsmohit097** [comment]
@nagalakshmi08 want to work on this issue?
u have to integrate the login and signup with frontend and backend

**Comment by nagalakshmi08** [comment]
> @nagalakshmi08 want to work on this issue? u have to integrate the login and signup with frontend and backend

Yes, i would like to work on this issue.

**Comment by itsmohit097** [comment]
@nagalakshmi08 assigned to u. The work is only on the frontend part. Also do the auth part. I will add level 3 label.
Can you complete it by today positively?
[Important] :
Do not waste your precious time. Kindly do the fork and branch process properly (read contribution.md file)
If not followed properly PR will not be merged and the issue will be assigned to another contributor.

**Comment by pspriyanshu601** [comment]
hey @itsmohit097 please assign this to me as well, the better of the two prs can be merged :)

**Comment by nagalakshmi08** [comment]
> @nagalakshmi08 assigned to u. The work is only on the frontend part. Also do the auth part. I will add level 3 label. Can you complete it by today positively? [Important] : Do not waste your precious time. Kindly do the fork and branch process properly (read contribution.md file) If not followed properly PR will not be merged and the issue will be assigned to another contributor.

Hello @itsmohit097 , apologies for the delayed response. I've made adjustments to the frontend fields in the signup and login pages based on the user models defined in usermodels.js. However, I'm encountering difficulties in establishing a connection with the backend, as I'm receiving multiple errors related to CORS and Axios.

**Comment by itsmohit097** [comment]
@nagalakshmi08 i provided the .env.example file in backend folder 
duplicate that file and rename it as .env
replace the placeholdesr with actual credentials

**Comment by nagalakshmi08** [comment]
> @nagalakshmi08 cors error : http://localhost:(backend running port)/api/v1/(api u r using) Axios error : replace imoort statement : import axios from "axios"
> 
> tag me if there is any other issue we have to complete it by today(31st)

@itsmohit097 , The signup process is functioning correctly, with data being successfully stored in the database. 
![Screenshot 2024-05-31 131707](https://github.com/itsmohit097/medi-hub/assets/121669832/4fc019b5-cab5-4fc6-93cf-c9be49668010)
However, upon loading the login page, an error related to cookies is occurring, which is preventing further actions from taking place.
![Screenshot 2024-05-31 131752](https://github.com/itsmohit097/medi-hub/assets/121669832/774c0eba-580e-4af2-ba05-7e66e7d677df)

**Comment by itsmohit097** [comment]
Ok @nagalakshmi08 
Raise the PR . I will look into this.

**Comment by ShampaShaw** [comment]
can you please assign this to me
