### ISSUE TITLE
[BUG]: SignUp &LogIn

### ISSUE THREAD

**Issue by omneaa** [itsmohit097/medi-hub#106]
SignUp & login not work and have bug in server Side

this is the image bug:-
![MediHub - Google Chrome 5_15_2024 1_19_25 AM](https://github.com/itsmohit097/medi-hub/assets/80198144/6f36946e-5f8e-4a2b-88ee-ab5da1c8b93f)

I can fix this bug in server side 
plz assign to me this task am GSSoC'24 contributor

**Comment by itsmohit097** [comment]
Assigned to someone elsse
