### ISSUE TITLE
Login-Signup authentication using mongodb

### ISSUE THREAD

**Issue by sahithi000** [itsmohit097/medi-hub#11]
I can provide the login and signup authentication please assigh this task for me by labelling it as gssoc

**Comment by Tarun2605** [comment]
I am interested in this task. Please assign it to me under gssoc.

**Comment by ManpreetSingh18** [comment]
I'm eager to contribute to the "Login-Signup authentication using MongoDB" task Under GSOC. Here's how I propose to approach it:

2. **Secure Password Storage**: Using bcrypt hashing, I'll ensure passwords are securely stored and authenticated from MongoDB.

4. **JWT Token Generation**: I'll implement JWT token generation upon successful login for secure authentication.

5. **Middleware for Protected Routes**: I'll integrate middleware to ensure that only authenticated users can access sensitive parts of the app.

6. **Error Handling and Feedback**: I'll handle authentication errors gracefully for an improved user experience by having a middleware for an error page.

I've previously implemented similar functionality using MongoDB Atlas Cloud, demonstrated in [this project](https://github.com/ManpreetSingh18/tavPrasad). 

Excited to contribute to the project!

Best regards,
Manpreet Singh
msingh.18.2001@gmail.com

**Comment by itsmohit097** [comment]
Login and Signup authentication is already done by me.
Someone is already assigned for creating the Login and Signup pages.

**Comment by dushyant2909** [comment]
I'm interested in working on the authentication feature for login and signup using MongoDB.
I have experience with MongoDB and authentication systems, and I'm eager to contribute.
