### ISSUE TITLE
Add a FAQ Section to the Website

### ISSUE THREAD

**Issue by Sakshar-Devgon** [itsmohit097/medi-hub#115]
Hello , My name is "Sakshar Devgon"

https://github.com/itsmohit097/medi-hub/assets/121454018/b2c837fc-075e-4eed-ba36-f1f3a3b2518a

I would like to propose adding a Frequently Asked Questions (FAQ) section to the website. This section will help users find answers to common questions related to medical treatments. Below is the proposed HTML, CSS, and JavaScript for the FAQ section:, i have sended you the faq sample in the form of video ,, kindly assign me in this then i will do the styling of this faq section acc to you ui and then i will send the pull request ...
thank you 
kindly accept its a great thing to add faq section ( i attached the sample in preview section) i will design it acc to your ui when you assign it to me

**Comment by itsmohit097** [comment]
@Sakshar-Devgon assigned to someone else
