### ISSUE TITLE
Implement Google Signup Functionality

### ISSUE THREAD

**Issue by srivastav2006** [itsmohit097/medi-hub#119]
## Description

 Users should be able to sign up using their Google tokens for authentication.

This feature enhances user convenience by allowing them to sign up using their Google accounts, reducing the need to remember additional login credentials.

## Screenshots 

Actual:
![image](https://github.com/itsmohit097/medi-hub/assets/143505484/65bacfb0-aa40-453a-9636-9a86c9e32f4d)

Expected :
![image](https://github.com/itsmohit097/medi-hub/assets/143505484/e7311d25-a965-4eb8-a773-d6199c525c0f)

Could you please Assign this issue to me under gssoc

**Comment by itsmohit097** [comment]
already assigned to someone else
