### ISSUE TITLE
Adding Login and Signup pages with jwt authentication

### ISSUE THREAD

**Issue by BhavaniSaranga12** [itsmohit097/medi-hub#12]

**Comment by ManpreetSingh18** [comment]
I am interested in this task. Please assign it to me under gssoc.
I propose to:
1. Implement a Signup page where new users can register by providing necessary information such as username, email, and password.
2. Ensure that passwords are securely hashed before storing them in the database using bycrypt hashing.
3. Implement a Login page where existing users can enter their credentials to access the application.
4. Upon successful login, generate a JWT token and send it to the client to be stored securely (e.g., in local storage or cookies).
5. Implement middleware to validate JWT tokens for protected routes, ensuring that only authenticated users can access certain parts of the application.
6. Handle authentication errors gracefully and provide appropriate feedback to users.
7. Secure API endpoints by verifying JWT tokens before allowing access to sensitive data or operations
I have earlier also implemented this type of functionality in one of my projects.You can check out at [https://github.com/ManpreetSingh18/tavPrasad](url)

**Comment by itsmohit097** [comment]
I have already done Login and Signup authentication.
Someone is already assigned to create the Login and Signup pages.
Once the pages are created I will assign them to you for backend integration.
