### ISSUE TITLE
[ENHANCEMENT STYLING]  Navabar is not fixed at top !!

### ISSUE THREAD

**Issue by SrijaVuppala295** [itsmohit097/medi-hub#121]
## Description

Navbar is not fixed at the top.

## Actual Behavior

Navbar scrolls with the page instead of staying fixed at the top.

## Expected Behavior

Navbar should remain fixed at the top while scrolling.

## Steps to Reproduce (if applicable)

1. Step 1   Scroll down the webpage.
2. Step 2   Observe the navbar's position.
3. Step 3   Notice it scrolls with the page content instead of remaining fixed at the top

## Screenshots (if applicable)

Actual:
(screenshot)

The navbar is not visible

![Screenshot 2024-05-17 004830](https://github.com/itsmohit097/medi-hub/assets/140592148/5585d0c5-f3c8-40d9-875d-801717d31ab9)

Expected (highlight the part that requires changes):
 
The navbar should be visible even if we scroll down!!
![image](https://github.com/itsmohit097/medi-hub/assets/140592148/2bb931da-2009-4415-8f63-59620f397491)

**Comment by SrijaVuppala295** [comment]
Please assign me !!

**Comment by itsmohit097** [comment]
no need to make navbar fixed at top
