### ISSUE TITLE
Login/Signup Functionality Accepts Wrong Credentials , url routing and also media queries for mobile view

### ISSUE THREAD

**Issue by Ramu-chiluveru** [itsmohit097/medi-hub#122]
The login/signup functionality of the application incorrectly indicates a successful login even when wrong credentials are entered. This issue compromises security and user experience by allowing unauthorized access and providing false feedback.

Steps to ReproduceNavigate to the login/signup page.Enter invalid or incorrect credentials (e.g., wrong username or password).Click the "Login" or "Signup" button.Observe that the system displays a message indicating a successful login, despite the credentials being incorrect.

Expected BehaviorThe system should validate the credentials against the database. If the credentials are incorrect:The system should display an appropriate error message (e.g., "Invalid username or password").The user should not be granted access to the application.
<img width="960" alt="Screenshot 2024-05-17 122242" src="https://github.com/itsmohit097/medi-hub/assets/101164811/442c5920-422e-4b85-a4ce-9172d8fc9a4a">
<img width="960" alt="Screenshot 2024-05-17 122305" src="https://github.com/itsmohit097/medi-hub/assets/101164811/9c178ffb-69fa-4007-b716-fae3b220cf33">

The URL routing in the application is not functioning correctly, which can cause users to experience broken links or incorrect navigation within the application.Steps to ReproduceNavigate to the application.Attempt to access various routes (e.g., /login, /signup, /dashboard).Observe that the application either does not navigate correctly, displays a 404 error, or fails to render the correct components.

**Comment by Ramu-chiluveru** [comment]
As a GSsoc'24 contributor. I want to work on this issue. So, I request you to assign this task to me
@itsmohit097

**Comment by itsmohit097** [comment]
already assigned to someone else
