### ISSUE TITLE
[Feat]: Adding 404 error page

### ISSUE THREAD

**Issue by Samani-Humaira** [itsmohit097/medi-hub#123]
## Description

Adding a 404 error page ensures that if a user accidentally requests an incorrect route, they will not receive any inconvenient response.

## Actual Behavior

Now,if user by mistake go to this url (https://medi--hub.vercel.app/Dashboard) it is showing irrelevant error

## Expected Behavior

Please describe what you expected to happen.

So , if user by mistake go to any route that does not exist he/she should get a custom error page that allow them to navigate to the websites home page or a route that exist.

## Screenshots (if applicable)

Actual:

![image](https://github.com/itsmohit097/medi-hub/assets/142516438/bd4bd505-aaba-4bd9-b6e8-3166b5ae712a)

Expected (highlight the part that requires changes):
He should get proper page indicating that you are lost and allow them to navigate to the homepage of our website.

Hey @Arghyadeep09  please assign this to me under GSSOC'24

**Comment by itsmohit097** [comment]
@Samani-Humaira assigned
also try to  make UI suits our site(healthcare)
