### ISSUE TITLE
[BUG]: Content is behind navbar in All Doctor's page.

### ISSUE THREAD

**Issue by adarshjagati07** [itsmohit097/medi-hub#124]
## Description
There's a bug in the all doctors page, it is sticking to the top of the screen behind navbar
Please provide a brief description of the issue or feature request.

## Actual Behavior
Currently content is behind navbar

Please describe what actually happened.
When we click and go to the all doctors page it is sticking to the top of screen, showing adverse behaviour 

## Expected Behavior
Content should be present below the navbar.

Please describe what you expected to happen.

## Steps to Reproduce (if applicable)

1. Step 1: Open the website
2. Step 2: Go to the All Doctors section from Navbar
You will see it from there.

## Screenshots (if applicable)
![image](https://github.com/itsmohit097/medi-hub/assets/91245532/b1238a2b-bca2-42a2-ac77-8ae30a43057a)

I will clear this issue, please assign it to me under GSSOC'24. @itsmohit097

**Comment by itsmohit097** [comment]
the page is not ready yet 
some is already assigned for creating the page

**Comment by adarshjagati07** [comment]
Okay sure.. :)

**Comment by adarshjagati07** [comment]
Also navbar is not fixed at the middle position, it is floating at the top of the screen of nav have you assigned it to someone else? if not then i'll raise an issue related to it.
