### ISSUE TITLE
Bug : top to bottom icon needs to be fix in mobile view

### ISSUE THREAD

**Issue by kapilG0** [itsmohit097/medi-hub#127]
## Description

Top to bottom icon needs to be fix it overlaps the submit button of contact form in mobile view 

## Actual Behavior

Please describe what actually happened.

## Expected Behavior

Please describe what you expected to happen.

## Steps to Reproduce (if applicable)

1. Step 1
2. Step 2
3. Step 3

## Screenshots (if applicable)

Actual:
![Screenshot_20240517_195657](https://github.com/itsmohit097/medi-hub/assets/59639410/4d431de5-85f9-4ef1-b33c-44db1a9cbbbd)

Expected (highlight the part that requires changes):
(screenshot)

**Comment by itsmohit097** [comment]
@kapilG0 assigned to u.
[Important] : 
Do not waste your precious time. Kindly do the fork and branch process properly (read contribution.md file)
If not followed properly PR will not be merged and the issue will be assigned to another contributor.
