### ISSUE TITLE
Adding menubar

### ISSUE THREAD

**Issue by BhavaniSaranga12** [itsmohit097/medi-hub#13]
on smaller devices the navigation bar is invisible
![image](https://github.com/itsmohit097/medi-hub/assets/117339714/f1be76e8-eefd-46d2-a594-8a5bad84d9c0)

**Comment by thedarknight01** [comment]
I am interested in this task. Please assign it to me under gssoc.

**Comment by itsmohit097** [comment]
I have already assigned it to someone else.
Feel free to create new issues and make valid contributions.
