### ISSUE TITLE
add hover effect at header......

### ISSUE THREAD

**Issue by shuhaki** [itsmohit097/medi-hub#130]
## Description

Please provide a brief description of the issue or feature request.

## Actual Behavior

Please describe what actually happened.

## Expected Behavior

Please describe what you expected to happen.

## Steps to Reproduce (if applicable)

1. Step 1 make icon realted to this website
2. Step 2 add hover effect
3. Step 3

## Screenshots (if applicable)

Actual:
(screenshot)

Expected (highlight the part that requires changes):
(screenshot)

**Comment by shreyaSup** [comment]
Hi ,please can you label it,I eould like to work on this issuse as a GSSOC'S contributor

**Comment by itsmohit097** [comment]
issue is not raised properly
