### ISSUE TITLE
Contact us is not arranged properly

### ISSUE THREAD

**Issue by Harsh22428** [itsmohit097/medi-hub#134]
![Screenshot: 2024-05-18 100851](https://github.com/itsmohit097/medi-hub/assets/143131675/f1185825-245f-4b14-bfed-cb7f348a4f93)

This contact us section is not arranged properly I want to make it more beautiful and attractive
please assign me this issue in GSSOC'24

Thank You

**Comment by itsmohit097** [comment]
i dont need any changes to this ryt now.
