### ISSUE TITLE
[ENHANCEMENT STYLING] : Adding "Top Specialities" section on the homepage

### ISSUE THREAD

**Issue by Samani-Humaira** [itsmohit097/medi-hub#137]
## Description

 Making Meet our talented team container to be scrollable.

## Actual Behavior

The "Meet Our Talented Team" container is not scrollable. As a result, when the screen size becomes smaller, only one or two cards are visible properly.

## Expected Behavior

It should be made scrollable so that when the screen size becomes small, all team members can be viewed by scrolling through the container.

## Screenshots (if applicable)

Actual:

![image](https://github.com/itsmohit097/medi-hub/assets/142516438/6ccce5d1-2a14-4b2f-a381-a466c7cb5f77)

Hey @itsmohit097  please assign me this under GSSOC'24

**Comment by itsmohit097** [comment]
@Samani-Humaira 
assigned to someone else
u can work on "our specialities section"
https://www.figma.com/design/eZiyFxl7zkLx9hE0Uz10zb/MediHub?node-id=0-1&t=wtd2LNGPlXQ5Orep-1
are u up for this issue?

**Comment by Samani-Humaira** [comment]
okay! I am working on "Top Specialities section" 

please assign me under GSSOC'24 @itsmohit097

**Comment by itsmohit097** [comment]
@Samani-Humaira assigned to u. Only make changes regarding to the issue (no other changes need to made)
[Important] : 
Do not waste your precious time. Kindly do the fork and branch process properly (read contribution.md file)
If not followed properly PR will not be merged and the issue will be assigned to another contributor.

**Comment by Samani-Humaira** [comment]
okay

**Comment by itsmohit097** [comment]
@Samani-Humaira update ??

**Comment by Samani-Humaira** [comment]
@itsmohit097 
sorry for the delay ,
I want to assure you that I am working on the task, and I will have it completed within the next 2-3 days.

**Comment by itsmohit097** [comment]
Ok @Samani-Humaira 
Try to complete asap
 Reminder : make it infinite slide

**Comment by Samani-Humaira** [comment]
Hi @itsmohit097 ,

Is the /appointment page something that we can work on? I'm really interested in handling that or any backend functionalities. Let me know!

**Comment by Saloni1723** [comment]
greetings @itsmohit097 even i would like to work on appointment page with @Samani-Humaira will u pls assign this to both of us !!!!

**Comment by Samani-Humaira** [comment]
@itsmohit097 any update regarding /appointment ?
