### ISSUE TITLE
[ENHANCEMENT FUNCTION] Making the logo in the navbar to be clickable so that it directs us to  Medi-Hub's homepage.

### ISSUE THREAD

**Issue by Samani-Humaira** [itsmohit097/medi-hub#138]
## Description

Currently, clicking on the logo in the navbar does not trigger any action. Instead, it should be configured so that clicking on it navigates the user to the home page of Medi-Hub.

## Actual Behavior

The logo in the navbar does not trigger any action.

## Expected Behavior

It should be configured so that clicking on it navigates the user to the home page of Medi-Hub.

## Screenshots (if applicable)

![image](https://github.com/itsmohit097/medi-hub/assets/142516438/79e5858f-3b60-41d9-a0e2-33df0032e3e6)

Hey @itsmohit097  please assign me this under GSSOC'24

**Comment by itsmohit097** [comment]
already done
