### ISSUE TITLE
ENHANCEMENT FUNCTION : Make Book Your appointment now page 

### ISSUE THREAD

**Issue by HimankPatidar** [itsmohit097/medi-hub#139]
## Description
On Home page book your appointment now button is added but it is not functional I can make Book Your appointment now page.

## Actual Behavior

The button does not trigger any action.

## Expected Behavior

It should open Book Your Appointment Now page

Can you assign me this under GSSOC'24

**Comment by itsmohit097** [comment]
@HimankPatidar already assigned to someone else
