### ISSUE TITLE
[Enhancement]: Changing the fav icon and title of the web app

### ISSUE THREAD

**Issue by BhavaniSaranga12** [itsmohit097/medi-hub#14]

**Comment by Sumkaur02** [comment]
I can do this. Please assign me this issue under Gssoc'24.

**Comment by itsmohit097** [comment]
@Sumkaur02 I"ll assign this issue to you .
Also change the icon to logo.svg.
Kindly read the README.md and CONTRIBUTING.md file before the contribution.
I'll add the GSSOC label later you can start working on it.

**Comment by itsmohit097** [comment]
@Sumkaur02  are you working on it?

**Comment by Sumkaur02** [comment]
> @Sumkaur02 are you working on it?

Yes I have started working on it.

**Comment by itsmohit097** [comment]
@BhavaniSaranga12 
kindly make this change today only.
Before contributing fork the repo properly (read contribution.md file).
If not followed properly it will not be accepted.
if you need any assistance tag me here

**Comment by Sumkaur02** [comment]
@itsmohit097 I just want to know which one of these you will prefer 
![IMG-20240512-WA0006](https://github.com/itsmohit097/medi-hub/assets/144603204/72db4e10-a516-43a5-af2b-5dabbe2a6c23)

**Comment by Sumkaur02** [comment]
@itsmohit097 I just want to know which one of these you will prefer
![IMG-20240512-WA0008](https://github.com/itsmohit097/medi-hub/assets/144603204/d2ae93f5-c801-4d56-bb2c-b949ad613b80)

**Comment by itsmohit097** [comment]
Pick white one
