### ISSUE TITLE
BUG : Navbar is not responsive 

### ISSUE THREAD

**Issue by HimankPatidar** [itsmohit097/medi-hub#140]
## Description

Navbar is not behave responsive as you decrease the width of device after reaching certain We can't even get access to  Navbar.
## Actual Behavior
Navbar element disappear when width of device or screen become less

## Expected Behavior
A bar button should be there so that when device reach certain height we can access the element of navbar from there.

![Screenshot 2024-05-18 195541](https://github.com/itsmohit097/medi-hub/assets/87924614/b0dfde87-c6e3-4e7d-a3df-b4f0231d765b)
Can you assign me this issue under GSSOC'24

**Comment by itsmohit097** [comment]
already solved the navbar issue
