### ISSUE TITLE
Add Password Strength Guidelines and "Show Password" Feature to Registration Page

### ISSUE THREAD

**Issue by kushalkumar1362** [itsmohit097/medi-hub#141]
### Description

To enhance user security and usability, it is important to provide clear and concise guidelines for creating strong passwords and the ability to toggle password visibility on the registration page. I suggest including the following password requirements and guidelines, along with a "Show Password" feature.

Here's an example of how the password strength indicator and guidelines can be displayed:
![331604926-626d221b-7341-4d85-af5d-3769a1762dae](https://github.com/itsmohit097/medi-hub/assets/140513098/0947a929-4dda-477a-b7cc-26a06305c19a)

### Benefits

1. Enhances user security by promoting strong password practices.
2. Reduces the risk of account breaches due to weak passwords.
3. Provides a clear and user-friendly interface for password creation.

### Implementation

1. Update the registration page to include a password strength meter.
2. Display the proposed guidelines next to the password input field.
3. Add a "Show Password" checkbox or icon to toggle password visibility.

### Additional:
The form will be hidden behind the navigation bar.
![image](https://github.com/itsmohit097/medi-hub/assets/140513098/a314fd7b-c073-49c4-a82c-762821776fe4)

**Comment by itsmohit097** [comment]
@kushalkumar1362 assigned to u

**Comment by amanjaiswal7236** [comment]
I want to work on it, can u please assign it to me
