### ISSUE TITLE
[Feat]: Added the all medicine pages and addTocart functionality enabled

### ISSUE THREAD

**Issue by tuwid-Ashish** [itsmohit097/medi-hub#142]
## Description
Hii @itsmohit097,

After adding the backend of medicine selling feature i would like to work on its Frontend part and provide a add to cart functionality along with the other medicine page for viewing all the medicine and also filter the required one.
Please provide a brief description of the issue or feature request.

**Comment by itsmohit097** [comment]
@tuwid-Ashish i made some changes in code. Kindly look through it.
Assigned this to u.

**Comment by itsmohit097** [comment]
@tuwid-Ashish update??

**Comment by tuwid-Ashish** [comment]
Hii @itsmohit097 

I will send you pull request by evening my frontend work is almost done , due to exams I was little busy ,not able to update.
