### ISSUE TITLE
[BUG] Login Functionallity Not Work Properly 

### ISSUE THREAD

**Issue by CoderSwarup** [itsmohit097/medi-hub#143]
## Description

When i try to login into the website it shows the log in successfully but their in website still showing the Login button 

## Actual Behavior

Please describe what actually happened.

## Expected Behavior

Please describe what you expected to happen.

## Steps to Reproduce (if applicable)

1.go to login page
2.sign in with credentials 
3.notice their is still showing login button and you can access login functionallity

## Screenshots (if applicable)

Actual:
(screenshot)

Expected (highlight the part that requires changes):
(screenshot)

please assign me this issue i want to work on that

**Comment by itsmohit097** [comment]
already assigned to someone else
