### ISSUE TITLE
ENHANCEMENT FUNCTION : Add sliding functionality to contributor cards.

### ISSUE THREAD

**Issue by nagalakshmi08** [itsmohit097/medi-hub#145]
## Description

The contributor cards were not moving, only few cards were appearing.

## Expected Behavior

If a sliding bar is added, we can view all contributors and using space efficiently.

## Screenshots (if applicable)

![image](https://github.com/itsmohit097/medi-hub/assets/121669832/3a641d96-e8cd-47d8-9621-45d9a20f1312)
I would like to add a sliding functionality to cards . Please assign me this issue under GSSoC'24.

**Comment by annoy004** [comment]
can you please assign me this issue
\

**Comment by itsmohit097** [comment]
@nagalakshmi08 already assigned to someone else
