### ISSUE TITLE
BUG: Sign up overlapped

### ISSUE THREAD

**Issue by dhruv8433** [itsmohit097/medi-hub#148]
@itsmohit097 

## Description
Sign up overlapped and hide in navigations

Please provide a brief description of the issue or feature request.

## Actual Behavior
- it hide after navigation
Please describe what actually happened.

## Expected Behavior
- it should look center of the page
Please describe what you expected to happen.

## Screenshots (if applicable)

Actual:
(screenshot)
![image](https://github.com/itsmohit097/medi-hub/assets/114583978/8eac8c8f-21af-48a6-8fab-2a7d35daf1fd)

Expected (highlight the part that requires changes):
this signup div come in center

**Comment by itsmohit097** [comment]
Already solved this issue
