### ISSUE TITLE
BUG: Signup Validations

### ISSUE THREAD

**Issue by dhruv8433** [itsmohit097/medi-hub#149]
@itsmohit097 

## Description

Please provide a brief description of the issue or feature request.

## Actual Behavior
- signup work without any infomration

## Expected Behavior
- we add validation in signup so if there are any missing value we gor error message

Please describe what you expected to happen.
when we click on signup withouot any information, it still display toast message with 
"Form submitted success"

## Steps to Reproduce (if applicable)

1. Step 1 we can add validations using js

## Screenshots (if applicable)

Actual:
(screenshot)
![image](https://github.com/itsmohit097/medi-hub/assets/114583978/ced7878f-b6f7-4102-bfff-2db0dd765d50)

**Comment by itsmohit097** [comment]
@RanjanaShenoy @dhruv8433 already assigned to someone else
