### ISSUE TITLE
Add login and signup functionality using jwt token

### ISSUE THREAD

**Issue by tuwid-Ashish** [itsmohit097/medi-hub#15]
Hii @itsmohit097 

I would like to add login and signup page functionality  with database integration and also the google Auth service to medihub under the GSSOC'24. 

and please do label this issue with GSSOC'24 , So that this contribution can be counted.

thanks

**Comment by ManpreetSingh18** [comment]
I am interested in this task. Please assign it to me under gssoc.
I propose to:

Implement a Signup page where new users can register by providing necessary information such as username, email, and password.
Ensure that passwords are securely hashed before storing them in the database using bycrypt hashing.
Implement a Login page where existing users can enter their credentials to access the application.
Upon successful login, generate a JWT token and send it to the client to be stored securely (e.g., in local storage or cookies).
Implement middleware to validate JWT tokens for protected routes, ensuring that only authenticated users can access certain parts of the application.
Handle authentication errors gracefully and provide appropriate feedback to users.
Secure API endpoints by verifying JWT tokens before allowing access to sensitive data or operations
I have earlier also implemented this type of functionality in one of my projects.You can check out at [https://github.com/ManpreetSingh18/tavPrasad](https://github.com/itsmohit097/medi-hub/issues/url)

**Comment by Tarun2605** [comment]
I am interested in this, I can provide you custom username and password login with jwt token or I can also set up a google OAtuh 2.0 login.

**Comment by itsmohit097** [comment]
> I am interested in this, I can provide you custom username and password login with jwt token or I can also set up a google OAtuh 2.0 login. Please assign me under gssoc'24

I have already done Login and Signup authentication.
Someone is already assigned to create the Login and Signup pages.
Once the pages are created I will assign them to you for OAuth2.0.

**Comment by dushyant2909** [comment]
Hi there! I'd like to take on this issue and implement the login and signup functionality using JWT tokens.
It's an area I'm familiar with and excited to work on. Could you please assign this issue to me? Thanks!
