### ISSUE TITLE
FEAT: Add 404 Page

### ISSUE THREAD

**Issue by dhruv8433** [itsmohit097/medi-hub#150]
@itsmohit097 

## Description
- there is not 404 : not found page
it is very simple

## Steps to Reproduce (if applicable)
we can redesign 404  not found page

## Screenshots (if applicable)

Actual:
(screenshot)
![image](https://github.com/itsmohit097/medi-hub/assets/114583978/8b4a4c84-a741-4f70-b08b-4d1829b942c0)

Expected (highlight the part that requires changes):
(screenshot)
![image](https://github.com/itsmohit097/medi-hub/assets/114583978/c9fa02f8-d6e3-416e-9a8f-9c46cd49d3da)

**Comment by kavyachandarkar** [comment]
@itsmohit097 please assign this to me. I am a contributor in GSSOC 2024 and want to work on this issue

**Comment by itsmohit097** [comment]
@dhruv8433  
Another contributor already adds an error page. Kindly look for new issue and raise it.
