### ISSUE TITLE
FEAT: Add Burger Menu in Responsive

### ISSUE THREAD

**Issue by dhruv8433** [itsmohit097/medi-hub#151]
@itsmohit097 
## Description

- there is no burger menu in responsive design 

Please provide a brief description of the issue or feature request.
- there is not any burger menu that provide direct link of any page 
- we can add burger menu for that

## Screenshots (if applicable)

Actual:
(screenshot)
![image](https://github.com/itsmohit097/medi-hub/assets/114583978/4975610e-f856-4352-bbd7-1aecdbef8b81)

**Comment by itsmohit097** [comment]
@dhruv8433 already assigned to someone else
