### ISSUE TITLE
reDesign the Home Img

### ISSUE THREAD

**Issue by Varsani2520** [itsmohit097/medi-hub#152]
@itsmohit097 ,
## Description

redesign the Img :add random vector graphics behind the img
before:
![image](https://github.com/itsmohit097/medi-hub/assets/137641079/3004720d-9162-413b-971f-f302967a246f)

after:
![image](https://github.com/itsmohit097/medi-hub/assets/137641079/240dbbc4-0b7d-44ef-8989-d42ea745ccc1)

**Comment by itsmohit097** [comment]
@Varsani2520 new hero section is added
