### ISSUE TITLE
overlap the all pages

### ISSUE THREAD

**Issue by Varsani2520** [itsmohit097/medi-hub#153]
@itsmohit097 ,
## Description

Please provide a brief description of the issue or feature request.
all the pages are some portion are hide behind the navigation
![image](https://github.com/itsmohit097/medi-hub/assets/137641079/f7662e0d-1f28-4336-8382-dbf987503210)

**Comment by itsmohit097** [comment]
1

**Comment by itsmohit097** [comment]
already fixed
