### ISSUE TITLE
[Enhancement Styling] : New Ui of login and signup page

### ISSUE THREAD

**Issue by Varsani2520** [itsmohit097/medi-hub#155]
@itsmohit097 ,
## Description

Please provide a brief description of the issue or feature request.
reDesign the login page 

user fell like a good and fun type
![image](https://github.com/itsmohit097/medi-hub/assets/137641079/8edc88d0-068f-4c9b-b065-92c78d1914c8)

like this:
![image](https://github.com/itsmohit097/medi-hub/assets/137641079/28f42d76-1156-4055-a0bf-4f3b365d5fcd)

**Comment by dev04sa** [comment]
@Varsani2520 , I can improve the UI of login page .
can you assign this issue to me.

**Comment by itsmohit097** [comment]
@Varsani2520 i need a better ui of login and signup page
do u want to work on this issue?

**Comment by Varsani2520** [comment]
Yes @itsmohit097 
If you assigned me i want to work on that

**Comment by itsmohit097** [comment]
@Varsani2520 please wait a moment. A contributor is currently working on the API integration. Once that is finished, I will assign you.

**Comment by Varsani2520** [comment]
Ok

**Comment by itsmohit097** [comment]
@Varsani2520 u can start working on this. 
As you can see it is a health related website. The images you use suits the theme.Also add smooth transitions.

**Comment by Varsani2520** [comment]
Hey @itsmohit097 ,so assigned me

**Comment by Varsani2520** [comment]
also add the gssoc and level 1 ,2,or 3 labeled
