### ISSUE TITLE
login validation

### ISSUE THREAD

**Issue by Varsani2520** [itsmohit097/medi-hub#156]
@itsmohit097 ,

if user click on login btn without fill the input field then display err toast for fill the form..
![image](https://github.com/itsmohit097/medi-hub/assets/137641079/75c32d91-1fd0-43c2-85d9-7b9a544d3121)

**Comment by dev04sa** [comment]
@itsmohit097 , I can fix this issue .
can you please assign this issue to me.

**Comment by itsmohit097** [comment]
duplicate issue and already assigned to someone else.
