### ISSUE TITLE
[FEAT] : Making the signup form to be fully functional by integrating with backend

### ISSUE THREAD

**Issue by Samani-Humaira** [itsmohit097/medi-hub#158]
## Description

To make the signup form functional, integrate it with the backend API. During signup, allowing  users to choose their role: "patient," "admin," or "doctor."

## Actual Behavior

Currently, logging in only displays a toast message and does not store the user's identity in the database. If the goal is to ensure that a user cannot become a doctor or patient without admin approval, I can implement that as well. However, we will first need to create the admin dashboard.

## Expected Behavior

The system should register the user, enabling access to various functionalities available only to logged-in or signed-up users.

Hey @itsmohit097 please assign this to me under GSSOC'24

**Comment by itsmohit097** [comment]
@Samani-Humaira already assigned to someone else
