### ISSUE TITLE
[Feature] : implement the appoinment page

### ISSUE THREAD

**Issue by sivaprasath2004** [itsmohit097/medi-hub#159]
## Description

- In this starting `home` page  `Book Your Appointment Now` can be click the page doesn't open the button also nothing to show.

## Actual Behavior

- If the button click `Navigate` to the `Appointment` page, but didn't work.

## Expected Behavior

- Appointment page can be  book `Doctor` and  the `Hospital`. 

## Steps to Reproduce (if applicable)

1. Step 1 : click the `Book Your Appoinment Now` button.
2. Step 2 : Doen't show nothing.
3. Step 3 : see the Feature request page.

**Comment by itsmohit097** [comment]
Already fiexed this issue
