### ISSUE TITLE
[BUG/ENHANCEMENT FUNCTION]

### ISSUE THREAD

**Issue by alfiyafatima09** [itsmohit097/medi-hub#163]
## Description

Sign-in/Sign-up doesn't work. The design needs to be improved and authentication must be added.

## Steps:

1. improve the design 
2. Use firebase for authentication

## Screenshots
![issue](https://github.com/itsmohit097/medi-hub/assets/139680721/a25e129e-02c9-4a85-9c90-4728df8b1938)

I would request you to assign me this issue under gssoc24.

**Comment by itsmohit097** [comment]
duplicate issue
