### ISSUE TITLE
[FEAT] reCAPTCHA Implementation

### ISSUE THREAD

**Issue by antriksh-9** [itsmohit097/medi-hub#168]
## Description

Implementing reCAPTCHA on the website will help in enhancing security, preventing spam and unauthorized access, protecting user data.
This also helps in preventing automated bots from accessing or submitting forms on the website.

## Actual Behavior

As of now spam bots can easily create fake accounts, or get unauthorized access, can be used for malicious purposes, etc.

## Expected Behavior

By implementing reCAPTCHA, a layer of security to protect against these threats is added.
reCAPTCHA helps ensure that the data collected from the forms is more likely to be valid and useful.

## Steps to Reproduce (if applicable)

1. Registering new site in reCATCHA Admin Console, adding domain name.
2. Site keys and Secret Key will be generated. 
3. Adding them in client-server and server.

## Screenshots (if applicable)

It will look similar to this: 

![Screenshot 2024-05-18 113014](https://github.com/itsmohit097/medi-hub/assets/132576984/025d9b28-4452-4f5b-b269-81c98b62f354)

**Comment by antriksh-9** [comment]
Hey @itsmohit097, I want to work on this issue. 
Please assign it to me under GSSoC '24.

**Comment by itsmohit097** [comment]
@antriksh-9 assigned
Important: Do the fork and branch process properly (read contribution.md file)
if not followed properly PR will not be merged

**Comment by antriksh-9** [comment]
@itsmohit097 I think you can close this issue now.

**Comment by itsmohit097** [comment]
Thnks for reminding @antriksh-9
