### ISSUE TITLE
[Bug]: Sticky navbar on scrolling 

### ISSUE THREAD

**Issue by siddxharth1** [itsmohit097/medi-hub#17]
We are not changing the value of the scrolled state when it meets the condition.
Can you please assign me this issue under gssoc.

**Comment by itsmohit097** [comment]
> We are not changing the value of the scrolled state when it meets the condition. Can you please assign me this issue under gssoc.

Explain it further and add screenshots

**Comment by siddxharth1** [comment]
![image](https://github.com/itsmohit097/medi-hub/assets/91618085/b3cfe996-8b10-4400-b99b-daf9bd66c4d3)
as you can see in the code we have inititalise the value with a false value and we are not updating its value when the condition meet so it will be false all the time.
and because of that this conditional statement wont work
![image](https://github.com/itsmohit097/medi-hub/assets/91618085/b1dd861b-187b-4102-87ea-d76dc0ee8a1c)

**Comment by itsmohit097** [comment]
@siddxharth1 assigned this to you
Kindly read the CONTRIBUTING.md files before the contribution by

**Comment by itsmohit097** [comment]
@siddxharth1 
kindly make this change today only.
Before contributing fork the repo properly (read contribution.md file).
If not followed properly it will not be accepted.
if you need any assistance tag me here
