### ISSUE TITLE
[ENHANCEMENT STYLING] : Adding a logo on the navbar

### ISSUE THREAD

**Issue by prachita0504** [itsmohit097/medi-hub#170]
## Description
LOGO IS SO SIMPLE 

PLEASE ASSIGN THIS TO ME AS I'M UNDER GSSOC'24. I CAN MAKE MORE BEAUTIFUL LOGO FOR THIS

**Comment by itsmohit097** [comment]
@prachita0504 assigned to u
[Important] : 
Do not waste your precious time. Kindly do the fork and branch process properly (read contribution.md file)
If not followed properly PR will not be merged and the issue will be assigned to another contributor.
