### ISSUE TITLE
[ ENHANCEMENT STYLING ] :   Improve The styling in  Doctors Cards Design

### ISSUE THREAD

**Issue by dhruv389** [itsmohit097/medi-hub#171]
Please assign me this issue.

## Screenshots (if applicable)

![Screenshot 2024-05-26 022353](https://github.com/itsmohit097/medi-hub/assets/117587892/e9792de0-1157-4693-a9da-e57055bd86c7)

**Comment by itsmohit097** [comment]
@dhruv389 already done
