### ISSUE TITLE
[ENHANCEMENT STYLING] Improve UI of the all doctors card

### ISSUE THREAD

**Issue by pspriyanshu601** [itsmohit097/medi-hub#174]
## Description

Currently the all the doctors card looks too colourful and does not match the theme of the rest of the website .
So I want to improve the UI of those cards. 

## Expected Behavior

Doctors card should match the theme of the website .

## Screenshots (if applicable)

Actual:
<img width="492" alt="Screenshot 2024-05-26 at 12 20 44 PM" src="https://github.com/itsmohit097/medi-hub/assets/105817879/cc8a704c-9d62-4956-b84b-b79887280e93">

Expected :
Will update after making new UI but it will follow the rest of the websites theme .

**Comment by pspriyanshu601** [comment]
@itsmohit097 please assign this issue to me, I want to work on this issue

**Comment by itsmohit097** [comment]
@pspriyanshu601 assigned
Can you complete it by today?

**Comment by pspriyanshu601** [comment]
yes , I will send the pr by today evening .
Thanks for assigning 😊.

**Comment by pspriyanshu601** [comment]
Hey @itsmohit097 , can you please review the pr I made , and suggest changes if any .
Thanks in advanced.
