### ISSUE TITLE
[BUG]: Back to Top button not visible when scrolling

### ISSUE THREAD

**Issue by Saimanjari777** [itsmohit097/medi-hub#175]
## Description

The back to top button is not visible when the website is scrolled. It is hiding under the text. 

## Actual Behavior

The button should be present above the text and should not hide under the text. 

## Expected Behavior

I would like to fix this issue by adding the z index to it 

Expected (highlight the part that requires changes):
![1716717140789](https://github.com/itsmohit097/medi-hub/assets/130165687/9b77f186-0d69-441f-8a66-0efa0d2b8c18)

**Comment by itsmohit097** [comment]
@assigned to someone else
duplicate issue
