### ISSUE TITLE
Duplicate Navbars on All Doctors Page

### ISSUE THREAD

**Issue by jency1** [itsmohit097/medi-hub#178]
## Description

The all doctors page on our website is currently displaying two navigation bars, which creates confusion and disrupts the user experience. This issue needs to be resolved by removing the redundant navbar and ensuring only one navbar is displayed.

## Actual Behavior

2 Navbars in All Doctors page

## Expected Behavior

There should be only one navbar displayed at the top of the all doctors page, consistent with the rest of the website.

## Steps to Reproduce (if applicable)

1. Identify and remove the redundant navbar from the all doctors page.
2. Ensure the remaining navbar is correctly styled and functions as intended.
3. Verify that the change is consistent with the overall website design.

## Screenshots (if applicable)

Actual: [2 navbars - All Doctors Page](https://github.com/itsmohit097/medi-hub/assets/149723236/a6eca167-2147-4771-82e3-34997b2747ea)

Having duplicate navbars can confuse users and clutter the interface. Ensuring a single, consistent navbar across all pages is crucial for a seamless and professional user experience.

I'm GSSOC'24 Contributor.

Please assign this issue to me, as I would like to resolve this problem as soon as possible.

@itsmohit097

**Comment by itsmohit097** [comment]
@jency1 assigned
