### ISSUE TITLE
Feature- ABOUT US

### ISSUE THREAD

**Issue by CS251000** [itsmohit097/medi-hub#18]
Add a responsive ABOUT US page to inform the user more about the project and its goals

Kindly assign it under GSSOC and a level

**Comment by itsmohit097** [comment]
> Add a responsive ABOUT US page to inform the user more about the project and its goals
> 
> Kindly assign it under GSSOC and a level

@CS251000 assigned this issue to you 
You can take the reference from the README.md file.
Kindly read the README.md and CONTRIBUTING.md file before the contribution.
I'll add the gssoc label later you can start working on it.

**Comment by saswat733** [comment]
hey kindly assign this issue to me would be delighted to work on this!!!!
