### ISSUE TITLE
[BUG/ENHANCEMENT FUNCTION] Login and Signup not working 

### ISSUE THREAD

**Issue by pspriyanshu601** [itsmohit097/medi-hub#184]
## Description

I want to implement the login and the signup functionality in the website .

## Actual Behavior

Currently , the website gives logged in successfully at any random username and password .

## Expected Behavior

Please describe what you expected to happen.

## Steps to Reproduce (if applicable)

1. I will use bcrypt for password hashing 
2. I will implement the entire login and signup page(both frontend and the backend)
3. In future we can also add the forgot password .

## Screenshots (if applicable)

Actual:
(screenshot)
<img width="808" alt="Screenshot 2024-05-28 at 10 52 52 AM" src="https://github.com/itsmohit097/medi-hub/assets/105817879/e64f3882-e74d-435d-ae5d-40131cb6c9c4">

Expected (highlight the part that requires changes):
(screenshot)
Will update after completion

**Comment by pspriyanshu601** [comment]
@itsmohit097 Please assign this issue to me , I will implement this within 2 hours of your assignment .

**Comment by itsmohit097** [comment]
@pspriyanshu601 already assigned to someone else
duplicate issue
