### ISSUE TITLE
[ENHANCEMENT STYLING] : Adding a new "Testimonial section" on the hompage

### ISSUE THREAD

**Issue by itsmohit097** [itsmohit097/medi-hub#187]
## Description

Don;t need to remove any other section. You just have to add a new testimonial section on the homepage

## Steps to Reproduce (if applicable)

1. Create a testimonials component
2. Render it on the homepage

## Screenshots (if applicable)

Expected (highlight the part that requires changes):
https://www.figma.com/design/eZiyFxl7zkLx9hE0Uz10zb/MediHub?node-id=0-1&t=wtd2LNGPlXQ5Orep-1

**Comment by dev04sa** [comment]
@itsmohit097  , I can work on this issue . kindly assign this issue to me.

**Comment by itsmohit097** [comment]
@dev04sa assigned to u. Only make changes regarding to the issue (no other changes need to made)
Follow the above mentioned steps
[Important] : 
Do not waste your precious time. Kindly do the fork and branch process properly (read contribution.md file)
If not followed properly PR will not be merged and the issue will be assigned to another contributor.

**Comment by dev04sa** [comment]
@itsmohit097  , Sure.

**Comment by pspriyanshu601** [comment]
hey ! @itsmohit097 can you please assign this issue to me as well , I can do it within an hour and since I have already made two contributions to your project, you wont have any compliance issues regarding following contribution.md .

**Comment by vaibhavi-singh-673** [comment]
Hi @itsmohit097 I want to work on this issue, can your assign me this.

**Comment by itsmohit097** [comment]
@vaibhavi-singh-673  assigned to u now.
Check the above instructions.

**Comment by vaibhavi-singh-673** [comment]
![image](https://github.com/itsmohit097/medi-hub/assets/104678215/6307e1e9-2b54-479d-9200-0e9cd9c96169)

I have made testimonial section  ready to merge it
