### ISSUE TITLE
[FEAT] : Adding the front-end for medicine 

### ISSUE THREAD

**Issue by itsmohit097** [itsmohit097/medi-hub#188]
## Description

You have to add a FrontEnd for medicine page. Backend is already written.

## Actual Behavior

No medicine page 

## Expected Behavior

Medicine page with all dynamic data.

## Steps to Reproduce (if applicable)

1. Create medicine folder in components and create file category, all featured(hint: backend)
2. Render all components on medicine page (create it)
3. Api integration 
4. Raise PR

## Screenshots (if applicable)

Actual:
(screenshot)

Expected (highlight the part that requires changes):
(screenshot)

**Comment by MitulSonagara** [comment]
@itsmohit097 I can work on this ... can you explain it more exactly what you need.

**Comment by pspriyanshu601** [comment]
Hey @itsmohit097 I would like to work on this issue ,I have already contributed to your project on a similar issue , I undertand what you need, please assign me this issue .
Thanks

**Comment by Harshsharmaa28** [comment]
@itsmohit097 i want to work on this
