### ISSUE TITLE
[ENHANCEMENT STYLING] : Adding a new "What is MediHub" section on the homepage

### ISSUE THREAD

**Issue by itsmohit097** [itsmohit097/medi-hub#191]
## Description

i want to add a new section "What is MediHub " on the homepage 

## Steps to Reproduce (if applicable)

1. Create a new component namely as WhatMedihub
2. Render it on homepage
3. Raise PR

Expected (highlight the part that requires changes):
https://www.figma.com/design/eZiyFxl7zkLx9hE0Uz10zb/MediHub?node-id=0-1&t=wtd2LNGPlXQ5Orep-1

**Comment by pspriyanshu601** [comment]
Hey @itsmohit097  I would like to work on this issue please assign this to me !!

**Comment by pspriyanshu601** [comment]
thanks for assigning , will send you PR by today evening itself

**Comment by pspriyanshu601** [comment]
raised the PR please review !!
