### ISSUE TITLE
[ENHANCEMENT STYLING] Improving the "Why choose us section"

### ISSUE THREAD

**Issue by pspriyanshu601** [itsmohit097/medi-hub#197]
## Description

Currently the Why choose us section is not matching the rest of website theme, I will make it exactly as the figma file desired for this project 

## Steps to Reproduce (if applicable)

1. Create a new component namely WhyUs
2. Render it on homepage
3. Raise a pr 

## Screenshots (if applicable)

Actual:
(screenshot)
<img width="1436" alt="Screenshot 2024-05-29 at 10 24 42 PM" src="https://github.com/itsmohit097/medi-hub/assets/105817879/2ae989b4-972a-4029-b666-c87303816f43">

Expected (highlight the part that requires changes):
(screenshot)

<img width="774" alt="Screenshot 2024-05-29 at 10 24 52 PM" src="https://github.com/itsmohit097/medi-hub/assets/105817879/fd8a65c8-db5b-4952-95d1-ea9c81d6c171">

**Comment by pspriyanshu601** [comment]
@itsmohit097 please assign this issue to me !!

**Comment by itsmohit097** [comment]
assigned to someone else
duplicate issue
