### ISSUE TITLE
[Feat]: Adding online medicine feature and set up the payment integeration

### ISSUE THREAD

**Issue by vivekbargude** [itsmohit097/medi-hub#2]
Description:
Introducing an online medicine ordering feature in Medihub to provide enhanced convenience for patients and healthcare providers. This feature will empower patients to seamlessly browse and order prescribed medications directly from the Medihub platform, streamlining the medication procurement process and elevating the overall user experience.

Benefits:

Convenient access to prescribed medications from the comfort of home, improving patient satisfaction and adherence to treatment plans.
Simplified ordering process for both patients and healthcare providers, reducing administrative burdens and enhancing operational efficiency.
Seamless integration with existing Medihub functionalities, ensuring a cohesive and comprehensive healthcare management platform.

Please assign it to me. I will work on it.

**Comment by itsmohit097** [comment]
what will yo do achieve this?
give a little description

**Comment by tuwid-Ashish** [comment]
Hii @itsmohit097 

I would like to work on this Feature backend or frontend part. I write down both my frontend and backend approach to implement this functionality. if you like any one of this please do assign me this task under GSSOC24

### My approach
Backend:
**Model:** Create a MedicineProduct model with relevant attributes such as:
name (string)
description (string)
price (Number)
stock (Number)
image (string, URL  path to an image file)

**Controllers:** Create a set of RESTful API endpoints for Admin management of medicine products:
POST /api/medicine-products: Create a new medicine product.
GET /api/medicine-products: Retrieve a list of all medicine products (use pagination for large datasets).
GET /api/medicine-products/:id: Retrieve a specific medicine product by ID.
PUT /api/medicine-products/:id: Update an existing medicine product.
DELETE /api/medicine-products/:id: Delete a medicine product (consider soft deletion for auditing purposes).
Implement robust validation and error handling on all API endpoints.

**Payment Gateway Integration:**
Integrate Stripe payment gateway to securely process payments.
Implement endpoints for creating and processing payments (e.g., POST /api/payments).
Handle payment confirmation, cancellation, and error scenarios.

Frontend:
**Medicine Listing:** Create a new route (/medihub/medicines) to display a list of all medicine products.
Fetch medicine product data from the backend API using a  axios or the fetch API.
Display medicine details (name, description, price, image) in a user-friendly manner.
Use pagination if there are a large number of products.

**Add to Cart and Purchase:**
Create an "Add to Cart" functionality  for users to select medicine products for purchase.
Store selected products in a shopping cart .
Implement a "Cart" page to display the selected products, quantity, and total price.
Provide a checkout process that allows users to enter their payment information and submit the order.
Integrate the Stripe payment gateway or chosen payment service with the checkout process.
Handle successful and failed purchases appropriately, providing informative feedback to the user.

**Comment by ayann07** [comment]
I can easily write backend for this , @vivekbargude you can do frontend part, please @tuwid-Ashish could you please assign me under GSSOC'24.

**Comment by itsmohit097** [comment]
> Hii @itsmohit097
> 
> I would like to work on this Feature backend or frontend part. I write down both my frontend and backend approach to implement this functionality. if you like any one of this please do assign me this task under GSSOC24
> 
> ### My approach
> Backend: **Model:** Create a MedicineProduct model with relevant attributes such as: name (string) description (string) price (Number) stock (Number) image (string, URL path to an image file)
> 
> **Controllers:** Create a set of RESTful API endpoints for Admin management of medicine products: POST /api/medicine-products: Create a new medicine product. GET /api/medicine-products: Retrieve a list of all medicine products (use pagination for large datasets). GET /api/medicine-products/:id: Retrieve a specific medicine product by ID. PUT /api/medicine-products/:id: Update an existing medicine product. DELETE /api/medicine-products/:id: Delete a medicine product (consider soft deletion for auditing purposes). Implement robust validation and error handling on all API endpoints.
> 
> **Payment Gateway Integration:** Integrate Stripe payment gateway to securely process payments. Implement endpoints for creating and processing payments (e.g., POST /api/payments). Handle payment confirmation, cancellation, and error scenarios.
> 
> Frontend: **Medicine Listing:** Create a new route (/medihub/medicines) to display a list of all medicine products. Fetch medicine product data from the backend API using a axios or the fetch API. Display medicine details (name, description, price, image) in a user-friendly manner. Use pagination if there are a large number of products.
> 
> **Add to Cart and Purchase:** Create an "Add to Cart" functionality for users to select medicine products for purchase. Store selected products in a shopping cart . Implement a "Cart" page to display the selected products, quantity, and total price. Provide a checkout process that allows users to enter their payment information and submit the order. Integrate the Stripe payment gateway or chosen payment service with the checkout process. Handle successful and failed purchases appropriately, providing informative feedback to the user.

@tuwid-Ashish explained very well
Assigned this issue to you.

Point to REMEMBER before contribution
-- fork the repo properly with all existing branches (read contribution.md file) if not followed properly PR will not be accepted
-- Check other backend files for code consistency

**Comment by itsmohit097** [comment]
@tuwid-Ashish I want the all-medicine page similar to this https://www.apollopharmacy.in/
just take a reference from this.

**Comment by tuwid-Ashish** [comment]
Hii  @itsmohit097 ,

please do update the Assignees to me as I  am currently working on this Feature

**Comment by itsmohit097** [comment]
@tuwid-Ashish assigned to you

**Comment by ayann07** [comment]
Please assign it to me

**Comment by itsmohit097** [comment]
@tuwid-Ashish update?
join discord https://discord.gg/krQd2Fss
