### ISSUE TITLE
All Doctors' Page 

### ISSUE THREAD

**Issue by aindree-2005** [itsmohit097/medi-hub#20]
Would like to design an all doctors Page with tags, contact, etc. Can I work on this? @itsmohit097

**Comment by GOKULGSECE** [comment]
As i have worked on Doctor-Appointment Booking System io have implemeneted an Doctors landing page where we can access the doctor's info like contact specialization details are mentioned in it so as i am a Contributor in Gssoc'24 would you  assign me this issue.

**Comment by aindree-2005** [comment]
I raised the issue as I wish to work on it @GOKULGSECE

**Comment by itsmohit097** [comment]
> I raised the issue as I wish to work on it @GOKULGSECE under GSSOC 2024

Do you design the page or implement the code at FrontEnd?

**Comment by GOKULGSECE** [comment]
Just implemented the doctor's informations as a cards where it contains the info's like contact details,in which the particular doctor is specialized in like that  and i have designed and also implemented in my project. hereby attaching the photo copy of that doctor's landing page
![Screenshot 2024-05-11 212948](https://github.com/itsmohit097/medi-hub/assets/125350820/3de736b9-cb54-4ac1-880e-7da4b7575023)

**Comment by itsmohit097** [comment]
@GOKULGSECE join discord we will discuss there afterward I'll assign u.

**Comment by GOKULGSECE** [comment]
> @GOKULGSECE join discord we will discuss there afterward I'll assign u.

How to join through discord as I don't find any links to do so @itsmohit097

**Comment by itsmohit097** [comment]
@GOKULGSECE https://discord.gg/eKaW3GqX join here

**Comment by GOKULGSECE** [comment]
> @GOKULGSECE https://discord.gg/eKaW3GqX join here
> 

I have joined @itsmohit097

**Comment by itsmohit097** [comment]
@GOKULGSECE 
Hoping you started working on this issue.
Don't forget to fetch-pull the repo as so many changes are made.

**Comment by GOKULGSECE** [comment]
@itsmohit097 I have a doubt to be clarified which is need to sorted out I have sent in discord plzncheck and reply asap

**Comment by developerdhruv** [comment]
I want to work on this issue and also can implement the doctors list in a good way
