### ISSUE TITLE
[BUG] The message text area is not fixed

### ISSUE THREAD

**Issue by ayush-848** [itsmohit097/medi-hub#202]
## Description
The message text area in the 'Contact Us' part is not fixed

## Expected Behavior
It should remain fixed

Please describe what you expected to happen.

## Steps to Reproduce (if applicable)

1. Step 1
2. Step 2
3. Step 3

## Screenshots (if applicable)

![image](https://github.com/itsmohit097/medi-hub/assets/126975547/b3d44ce2-d81a-4dc0-8d63-2ef34940911b)
![image](https://github.com/itsmohit097/medi-hub/assets/126975547/4019ee1b-dbd5-4433-ad5a-e1506bd3314b)

**Comment by itsmohit097** [comment]
ALready assigned to someone to make new footer
