### ISSUE TITLE
[FEAT]: Creating specialities card component

### ISSUE THREAD

**Issue by itsmohit097** [itsmohit097/medi-hub#203]
## Description

Top specialites page is empty now. Specailitis card should be display there.
[ ]HINT ] : Medicine page and component

## Steps to Reproduce (if applicable)
1. Create a component namely as TopSpecialitiesCard and render it on page TopSpecialites(to be created)
2. Adding loading effect (component already created) on the component and page
3. Create only one card with sample data (speciality name, img, desc,  symptomps)

## Screenshots (if applicable)

Expected (highlight the part that requires changes):
![Screenshot 2024-05-31 024551](https://github.com/itsmohit097/medi-hub/assets/125040386/55340058-61e5-4d3a-bce3-8f200dbfc8ee)

**Comment by itsmohit097** [comment]
@pspriyanshu601 want to work on this issue?

**Comment by pspriyanshu601** [comment]
yes @itsmohit097 , I want to work on this issue ,please assign this to me , I will make it within 1 hr

**Comment by itsmohit097** [comment]
@pspriyanshu601 assigned to u.
[Important] : 
Do not waste your precious time. Kindly do the fork and branch process properly (read contribution.md file)
If not followed properly PR will not be merged and the issue will be assigned to another contributor.

**Comment by vaibhavi-singh-673** [comment]
I even want to work on this issue can you assign me @itsmohit097

**Comment by pspriyanshu601** [comment]
please close this @itsmohit097
