### ISSUE TITLE
[FEAT] : Adding a order page

### ISSUE THREAD

**Issue by itsmohit097** [itsmohit097/medi-hub#206]
## Description
You have to create a order page exactly like flipkart order page. 

## Expected Behavior
Users can see the order details and history
Users can search the orders 

## Steps to Reproduce (if applicable)

1. Create a component namely as OrderedProduct 
2. Create a component namely as SearchOrderProduct
3. Render both components on orders page

## Screenshots (if applicable)
Expected (highlight the part that requires changes):
Search component
![image](https://github.com/itsmohit097/medi-hub/assets/125040386/1686ccb1-67a2-4997-bba0-aed50795c88d)
ordered component
![image](https://github.com/itsmohit097/medi-hub/assets/125040386/0ba20c33-dc2e-4c9c-85bf-9dd1f648fa2f)

## Display 4 OrderProduct component with sample data

**Comment by ayushkamboj18** [comment]
hey, I can do this. Can you explain from where I can get the data so that it can be rendered

**Comment by itsmohit097** [comment]
@ayushkamboj18 
You have to create a sample data.
I will make it dynamic later.

**Comment by ayushkamboj18** [comment]
ok, I can make it, assign me.

**Comment by ayushkamboj18** [comment]
hey, you marked this as closed but you also assigned me , can I start work or not

**Comment by itsmohit097** [comment]
@ayushkamboj18 i mistakenly close this. Start working on this and try to complete it asqp.
