### ISSUE TITLE
Dark Mode functionality

### ISSUE THREAD

**Issue by tusharyadav11** [itsmohit097/medi-hub#21]
I would like to contribute to Gssoc'24 and want to work under the functionality of crreating up the darkmode and light mode . i would be grateful if you could assign me this functionality @itsmohit097

**Comment by Himanshityagii24** [comment]
I can do this using react, please assign me this task

**Comment by itsmohit097** [comment]
@tusharyadav11 explain a little how will you implement this?

**Comment by itsmohit097** [comment]
@tusharyadav11 @Himanshityagii24 
I want this functionality on my dashboard wait till then

**Comment by tusharyadav11** [comment]
@itsmohit097  Added the DarkMode/LightMode functionality please check up my pull request .  Providing the screenshots for the sample purpose . 
![Screenshot 2024-05-17 171714](https://github.com/itsmohit097/medi-hub/assets/145464824/adc37c2b-d9cc-46b1-b01e-c753aae35d98)
![Screenshot 2024-05-17 171731](https://github.com/itsmohit097/medi-hub/assets/145464824/b6e057e6-d800-480b-b9c7-e1158356d40d)
![Screenshot 2024-05-17 171623](https://github.com/itsmohit097/medi-hub/assets/145464824/f0e855ce-18ca-44a3-8002-7527455f2961)
![Screenshot 2024-05-17 171527](https://github.com/itsmohit097/medi-hub/assets/145464824/5a1258bb-da18-4fde-b062-7439f5968dfc)
