### ISSUE TITLE
[BUG] placeholder misalignment

### ISSUE THREAD

**Issue by ayushkamboj18** [itsmohit097/medi-hub#211]
## Description
There is an error in the message textarea is a placeholder misalignment, caused by inconsistent CSS styles. 
![Screenshot from 2024-05-31 14-36-46](https://github.com/itsmohit097/medi-hub/assets/114069208/b049f288-0b3d-4348-a8c2-5d87dbc9326d)

**Comment by itsmohit097** [comment]
Someone is assigned for making new footer ui
