### ISSUE TITLE
Footer Not taking the full width making UI very dull

### ISSUE THREAD

**Issue by nitin-pandita** [itsmohit097/medi-hub#24]
![image](https://github.com/itsmohit097/medi-hub/assets/91310284/ff4ff07f-72ab-4deb-a4c0-aadaef534006)
Footer is not taking the full width

**Comment by nitin-pandita** [comment]
I can work on this issue, please assign this under gssoc

**Comment by Harshitazz** [comment]
assign me

**Comment by itsmohit097** [comment]
@nitin-pandita assigned to you.
Kindly read the CONTRIBUTING.md files before the contribution 
Make a whole new footer section matching with the existing theme

**Comment by nitin-pandita** [comment]
> @nitin-pandita assigned to you. Kindly read the CONTRIBUTING.md files before the contribution Make a whole new footer section matching with the existing theme

sure thing
