### ISSUE TITLE
Adding link to the Logo of navbar to get back to the home page

### ISSUE THREAD

**Issue by nitin-pandita** [itsmohit097/medi-hub#25]
![image](https://github.com/itsmohit097/medi-hub/assets/91310284/c7d3931c-bc75-4475-8c7f-6c7ad6979ee3)

**Comment by nitin-pandita** [comment]
Assign this to me under gssoc

**Comment by Tushar7436** [comment]
@itsmohit097 I would love to solve this issue, please assign me this issue
