### ISSUE TITLE
The Refresh on aany page gives 404 add vercel configuration

### ISSUE THREAD

**Issue by Utsavladia** [itsmohit097/medi-hub#253]
## Description
we need to add the vercel configuration so on Refresh it doesn't give 404 error

![image](https://github.com/itsmohit097/medi-hub/assets/124615886/908e2d35-e135-402e-b7cd-aa73475d96c3)

**Comment by Utsavladia** [comment]
Please assign this to me I would love to contribute to this project.

**Comment by thedarknight01** [comment]
Hey @Utsavladia, can you please provide the steps to reproduce this issue? I'm unable to verify it.

**Comment by Utsavladia** [comment]
Go on any page other than home page and  then refresh the page... you will get 404 error @thedarknight01

**Comment by itsmohit097** [comment]
@thedarknight01 @Utsavladia i myself working on this issue . I just have to correct my routes and their naming. Please look for another issue.
