### ISSUE TITLE
[ENHANCEMENT STYLING] Add hover text in footer

### ISSUE THREAD

**Issue by AkhilaSunesh** [itsmohit097/medi-hub#267]
## Description

Add hover text in footer
![image](https://github.com/itsmohit097/medi-hub/assets/140897461/2e35b3c6-e454-46b9-bcdc-79f71c4e2ee6)

## Actual Behavior

Add hover text

## Expected Behavior

Better readability

Expected (highlight the part that requires changes):
(screenshot)
![image](https://github.com/itsmohit097/medi-hub/assets/140897461/592c6737-3240-40e1-8256-b9b1ab65b022)

**Comment by itsmohit097** [comment]
Already assigned to someone else. Kindly not look for any other issue for 4 days🙏 im making some changes in the project.
