### ISSUE TITLE
[ Feature]: Adding appointment info page to the backend (user's dashboard)

### ISSUE THREAD

**Issue by haard18** [itsmohit097/medi-hub#27]
### Overview:
Introducing an Appointment Page with a user-friendly form and email integration will enable users to schedule appointments with doctors seamlessly. This feature aims to enhance the platform's functionality by providing a convenient way for users to book appointments and streamline communication between patients and doctors.

### Features:
1. **Login Redirect:**
   - If the user is not logged in, they will be redirected to the login page before accessing the Appointment Page.
   - Ensure that users are authenticated before proceeding to book appointments to maintain security and privacy.

2. **Appointment Form:**
   - Display a form for users to input necessary details such as name, contact information, reason for appointment, and preferred appointment time.
   - Include a dropdown menu to select available time slots for the doctors' appointments.
   - Implement form validation to ensure that required fields are filled out correctly before submission.

3. **Email Integration:**
   - Upon form submission, send an email notification to the doctor's email address with the appointment details.
   - Include patient information such as name, contact details, reason for appointment, and selected appointment time.
   - Add an "Add to Calendar" button/link in the email to allow doctors to easily add the appointment to their calendar application.

### Implementation Plan:
1. **Backend Development:**
   - Create backend routes and controllers to handle user authentication, form submission, and email notification.
   - Integrate with the platform's authentication system to enforce login before accessing the Appointment Page.
   - Implement email sending functionality using a suitable email service provider or SMTP server.

2. **Frontend Development:**
   - Design and develop the Appointment Page UI with the appointment form using HTML, CSS, and JavaScript.
   - Ensure that the form is user-friendly, accessible, and responsive across different devices and screen sizes.

3. **Email Templating:**
   - Create an email template for the appointment confirmation/notification email to be sent to doctors.
   - Customize the email template with dynamic placeholders to populate patient information and appointment details.

### Benefits:
- **Streamlined Appointment Booking:** The Appointment Page provides users with a simple and efficient way to schedule appointments with doctors.
- **Improved Communication:** Email integration ensures that doctors receive timely notifications about new appointments, facilitating better coordination and communication with patients.
- **Enhanced User Experience:** By offering a seamless booking process and email confirmation, the platform enhances the overall user experience and satisfaction.

**Comment by haard18** [comment]
I would Like to work on this under GSSOC'24

**Comment by ayann07** [comment]
I would like to work backend for this under GSSOC'24.

**Comment by itsmohit097** [comment]
@haard18  there is a appointment menu on user dashboard in that it'll show the user's info and doctor's info  
Frontend is not ready for this. You only have to write backend for this and test the api.
Hint : You have to write the aggregation pipeline for this process 
Changes: make changes in existing appointment form
Do you understand ?
U know how to write aggregation pipeline?

**Comment by haard18** [comment]
Yes I can give it a try! surething @itsmohit097

**Comment by itsmohit097** [comment]
> I would like to work backend for this under GSSOC'24.

@ayann07 join discord from the website i'll assiu some other backend work

**Comment by haard18** [comment]
is there a discord server where we can talk in depth about this? @itsmohit097

**Comment by haard18** [comment]
Assign this to me @itsmohit097

**Comment by ayann07** [comment]
Ok @itsmohit097
