### ISSUE TITLE
there is no login section assign me this task under GSSOC 24 

### ISSUE THREAD

**Issue by Venkatknight2295** [itsmohit097/medi-hub#29]
![WhatsApp Image 2024-05-11 at 06 36 43_8f8cda7c](https://github.com/itsmohit097/medi-hub/assets/118790430/664946c4-c749-4649-b685-824799718710)
there is no place to login assign me this task so that i can implement  that and change the UI to modern looking please lable this task and assign me to this @itsmohit097 @vickythegit

**Comment by mihirpatel07a** [comment]
i want that you assign this task to me . please assign me @itsmohit097  @Venkatknight2295
