### ISSUE TITLE
Missing Code of Conduct File in Repository

### ISSUE THREAD

**Issue by anshgautam-github** [itsmohit097/medi-hub#3]
Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behavior, ensuring that contributors and participants feel safe, respected, and valued within our community space.

Kindly assign me this issue, so i can work towards it under GSSOC 24

**Comment by itsmohit097** [comment]
Already added
Feel free to create new issues and do the contribution
