### ISSUE TITLE
[Enhancement Styling]: Added privacy policy page

### ISSUE THREAD

**Issue by Jagpreet153** [itsmohit097/medi-hub#30]
Please assign it to me under GSSoC'24

**Comment by itsmohit097** [comment]
@Jagpreet153 assigned to you.
Kindly read the contribution.md file (fork the repo properly and push changes in correct branch)

**Comment by Jagpreet153** [comment]
@itsmohit097 I have made privacy policy page matching with the UI of the site. The page is fully responsive .
If you are satisfied with the changes let me know so that I can generate the PR.

![Uploading Screenshot 2024-05-12 175241.png…]()

**Comment by Jagpreet153** [comment]
@itsmohit097 I have made privacy policy page matching with the UI of the site. The page is fully responsive .
If you are satisfied with the changes let me know so that I can generate the PR.

![Screenshot 2024-05-12 175241](https://github.com/itsmohit097/medi-hub/assets/119691733/c8993a65-ff10-4e79-bc0c-c96e3ce80ab2)

**Comment by itsmohit097** [comment]
@Jagpreet153 raise a PR.

**Comment by itsmohit097** [comment]
@Jagpreet153 request u to finish this bh today positively.
