### ISSUE TITLE
database connection issue

### ISSUE THREAD

**Issue by Harshitazz** [itsmohit097/medi-hub#31]
![h](https://github.com/itsmohit097/medi-hub/assets/118474653/cd5efb6b-59a4-433a-82c5-59721ece2927)

**Comment by Stacvirus** [comment]
hello @Harshitazz , I have some experience in building REST API and GraphQL servers and I hope to contribute on this issue. Thanks

**Comment by Himanshityagii24** [comment]
I have experience with MongoDB, and can solve this issue, can connect it to mongoose as well as MongoDB

**Comment by itsmohit097** [comment]
It is done purposely for now.
By today you all get a Discord server link
Join thereafter this error will not come

**Comment by kapilG0** [comment]
Hello @itsmohit097 can you please assign this issue to me
