### ISSUE TITLE
[ENHANCEMENT STYLING]: Adding a dropdown menu on hover at login button in navbar

### ISSUE THREAD

**Issue by SPraveenKumar-spk** [itsmohit097/medi-hub#33]
Issue : There is no user Profile section

Solution : I would like to add the features like fetching the user details like his/her bio data, past consulted doctors details, past appointments taken etc..

Please assign this me under gssoc24 . i would like to contribute to this project.

**Comment by itsmohit097** [comment]
@SPraveenKumar-spk
Add a downward menu when user hovers on login button (inside the login button)
Hint : flipkart website
Menu items will be : (my profile, appointments , wishlist, order, logout)
Add this to frontend no need to add functionality to the menu items
Can you implement this?

**Comment by SPraveenKumar-spk** [comment]
Yes I can implement this. Assign this to me under gssoc24

**Comment by itsmohit097** [comment]
@SPraveenKumar-spk assigned to u.
Request you to do fork and branch process properly (read contribution.md file).
if not followed properly PR will not be merged

**Comment by itsmohit097** [comment]
@SPraveenKumar-spk update ??

**Comment by SPraveenKumar-spk** [comment]
Hi admin, I have completed the coding, but while making the PR, facinig the following issue

C:\Users\prave\OneDrive\Documents\OpenSource\medi-hub>git checkout frontend
Updated 0 paths from the index

C:\Users\prave\OneDrive\Documents\OpenSource\medi-hub>git branch
* main

C:\Users\prave\OneDrive\Documents\OpenSource\medi-hub>git branch -a
* main
  remotes/origin/HEAD -> origin/main
  remotes/origin/main

C:\Users\prave\OneDrive\Documents\OpenSource\medi-hub>git fetch

C:\Users\prave\OneDrive\Documents\OpenSource\medi-hub>git branch
* main

C:\Users\prave\OneDrive\Documents\OpenSource\medi-hub>git branch -a
* main
  remotes/origin/HEAD -> origin/main
  remotes/origin/main
  
  Not switching to the frontend branch , I think there is no frontend branch do i need to create the front end branch and make PR?

**Comment by itsmohit097** [comment]
@SPraveenKumar-spk 
U don't do the fork properly thats why it is not showing that branch.
Raise the PR in main branch
