### ISSUE TITLE
[Enhancement Functionality/Styling] : Making navbar responsive (hamburger menu) and fix the bug hover effect on login

### ISSUE THREAD

**Issue by MitulSonagara** [itsmohit097/medi-hub#34]
All the navbar links are getting disappeared when i open in smaller size.

Screenshots:
![image](https://github.com/itsmohit097/medi-hub/assets/95460188/c43e0f14-2fb1-4ba9-a675-0842cfc08f05)
![image](https://github.com/itsmohit097/medi-hub/assets/95460188/44ff4e59-2f96-496c-9c6f-eac9c077c6da)

I will fix this.

Please assign me this issue under GSSOC'24.

**Comment by itsmohit097** [comment]
@MitulSonagara want to work on this issue?

**Comment by MitulSonagara** [comment]
@itsmohit097 Sure I will be Grateful to work on this...

**Comment by itsmohit097** [comment]
@MitulSonagara assigned to u. And also fix the hover effect on login, and make it properly visible.
[Important] : 
Do not waste your precious time. Kindly do the fork and branch process properly (read contribution.md file)
If not followed properly PR will not be merged and the issue will be assigned to another contributor.

**Comment by itsmohit097** [comment]
@MitulSonagara  i didn't assign this to other. Are u working on it or not?

**Comment by MitulSonagara** [comment]
@itsmohit097 Yes i am working on it... I'll make the PR by 11:00 tonight.

**Comment by itsmohit097** [comment]
ok

**Comment by pspriyanshu601** [comment]
hey @itsmohit097 please close this , this got merged
