### ISSUE TITLE
{Enhancement] : Removal of unnecessary picture 

### ISSUE THREAD

**Issue by MitulSonagara** [itsmohit097/medi-hub#35]
Get in touch section has a picture besides the form which is not matching the all over website and also if i open it in mobile there is no picture which will affect the User Experience. Also the alignment of form with the picture is not so good. So i will remove it or add any other substitute which can match properly.

![image](https://github.com/itsmohit097/medi-hub/assets/95460188/2f011c99-5d95-4d99-962e-046163a09933)

In mobile view
![image](https://github.com/itsmohit097/medi-hub/assets/95460188/32eebd44-e8c8-4352-8bf4-f6fefd6c8e9a)

Please assign me this under GSSOC'24.

**Comment by itsmohit097** [comment]
Stylings are already fixed and hiding the image under medium screens is done purposely.
