### ISSUE TITLE
Add Appointment page

### ISSUE THREAD

**Issue by ArtiGaund** [itsmohit097/medi-hub#38]
Can I create appointment page:-
a) Appointment booking form
-Patient's name
-Contact info
-Preferred date and time
-Reason for the appointment(health concern)
-Doctor preference

b) Doctor Schedule calender (if the doctor is available or not)

**Comment by ArtiGaund** [comment]
Ok I will do it

**Comment by itsmohit097** [comment]
@ArtiGaund want to work on this issue?
