### ISSUE TITLE
[FEAT]: Making navbar responsive

### ISSUE THREAD

**Issue by KhushiTiwarii** [itsmohit097/medi-hub#4]
![image](https://github.com/itsmohit097/medi-hub/assets/137861160/4d77b8eb-4671-4163-962d-8d11d3d864d1)

The navbar is not having all options in mobile view which it has in the desktop view

![image](https://github.com/itsmohit097/medi-hub/assets/137861160/e4a714e2-db02-427c-842a-3a0ac2f927a1)

Will add a hamburger menu which will have all the options

**Comment by ShoveetSingh** [comment]
hey mentor, i can easily make the navbar look more appealing to the eyes of visitors.
If given the chance.

**Comment by itsmohit097** [comment]
@KhushiTiwarii raised this issue first so I'll assign this issue to her.
Kindly read the README.md and CONTRIBUTING.md fiile before the contribution.
I'll add the gssoc label later you can start working on it.

**Comment by KhushiTiwarii** [comment]
Thankyou @itsmohit097 I'll start contributing !!

**Comment by KhushiTiwarii** [comment]
Hii I have made the navbar responsive by adding the hamburger menu and also fixed one more issue of sticky navbar, earlier it was not sticky.Kindly merge it

**Comment by itsmohit097** [comment]
@KhushiTiwarii are you working on it ??
