### ISSUE TITLE
Improve the UI of the home page and give a whole new look to the landing page by using Tailwind css

### ISSUE THREAD

**Issue by saswat733** [itsmohit097/medi-hub#42]
i will make use of tailwind css to create a whole new home page with eye catching fonts and bright color which please the users

**Comment by itsmohit097** [comment]
Can you show me some examples 
I really need a new ui.

**Comment by saswat733** [comment]
![Screenshot 2024-04-19 132840](https://github.com/itsmohit097/medi-hub/assets/75719949/03f5ceee-6d01-4287-8952-d8fedd439d6c)
![Screenshot 2024-04-19 132749](https://github.com/itsmohit097/medi-hub/assets/75719949/690de465-834c-424e-a3c8-de3ad5ffdeb4)
![Screenshot 2024-04-19 132600](https://github.com/itsmohit097/medi-hub/assets/75719949/7ac1877a-011e-4bf0-b142-c0d6f4cdf445)

these are just some examples how i can make your home page look like kindly assign me this under ggsoc level 3

**Comment by itsmohit097** [comment]
how will you do it 
i want to see preview before u write code 
do u know any design software (figma, adobe xd,etc.)
