### ISSUE TITLE
Login and Registration functionality for patient and doctor

### ISSUE THREAD

**Issue by VinayJangotra** [itsmohit097/medi-hub#44]
I can  add the functionality of login and register page and also then define the roles of doctor patient and admin i can define schema for the login and register page and write frontend code as well

**Comment by sahithi000** [comment]
@itsmohit097  can u please assign this task for me I can work on this functionality using MongoDb as well as firebase as I am familiar with both

**Comment by itsmohit097** [comment]
Login functionality is already added at the backend.
For frontend part someone is already assigned.
