### ISSUE TITLE
[Fix]: Correcting Copyright text

### ISSUE THREAD

**Issue by BHS-Harish** [itsmohit097/medi-hub#48]
Hey @itsmohit097  

I'm interest to change the title and favicon on title bar as well as change the copyright year as dynamically in the footer.

![image](https://github.com/itsmohit097/medi-hub/assets/114602603/16203560-33ae-4213-9500-169754248e0a)
![image](https://github.com/itsmohit097/medi-hub/assets/114602603/6f7fefca-bbda-4065-849f-80805eece923)

Please assign the issue to me
Thanks in advance

**Comment by itsmohit097** [comment]
@BHS-Harish for title someone is already assigned.
you can do the correction at the footer (only do the changes which is mentioned in the issue)
Replace DevUI with Mohit kumar
Assigned to you.

**Comment by mihirpatel07a** [comment]
hey i want to solve this issue please assign to me
