### ISSUE TITLE
Adding a medical assistance chatbot

### ISSUE THREAD

**Issue by KhushiTiwarii** [itsmohit097/medi-hub#5]
Will add a chatbot for user assistance using openai which will identify diseases based on symptoms given by the user and will also list medicine for the same. It will also assist in general medical doubts.Please assign me this under gssoc'24

**Comment by itsmohit097** [comment]
> Will add a chatbot for user assistance using openai which will identify diseases based on symptoms given by the user and will also list medicine for the same. It will also assist in general medical doubts.Please assign me this under gssoc'24

How will you implement this feature please explain?
Have you implemented this type of feature earlier?

**Comment by KhushiTiwarii** [comment]
I'll use google gemini llm for this. I've already worked with these features in my 2 hackathons.

**Comment by itsmohit097** [comment]
@KhushiTiwarii ur prev PR request is not properly followed contributing guidelines.
Assigned this issue to you.

**Comment by avneetsingh154** [comment]
hi @itsmohit097 i want to work upon this issue along with my friend @kaashish1111 . We will train rasa on bert for it . we aslo have previous experience in this as we have trained rasa on ISRO bhuvan data for the isro space hackathon and our project was also praised by ISRO's chairman Dr. S Somnath . please assign this project to us under Gssoc24.

**Comment by avneetsingh154** [comment]
ok, @itsmohit097 sir will be waiting for a prompt reply.

**Comment by HYDRAEZIO** [comment]
@itsmohit097  i have already have a model related medical knowledge as i have developed it for my personal project which helps to find nearby location of the doctor and the ambulances presesnt further we can train the model as per the requirement for the website . We can also train the for the first aid and if required will also appoint the nearby doctor . please assign this project to us under Gssoc24.

**Comment by KhushiTiwarii** [comment]
@itsmohit097 sorry for the delay I'll push my code by day after tommorrow 
sorry for taking time as I had got my end term exams in between.

**Comment by itsmohit097** [comment]
@KhushiTiwarii focus on ur exams as for this feature we can implement it later when u start working it  just ping me on discord.

**Comment by itsmohit097** [comment]
@KhushiTiwarii are u working on this issue now??

**Comment by itsmohit097** [comment]
@avneetsingh154 want to work on this issue

**Comment by KhushiTiwarii** [comment]
@itsmohit097 I have made the chatbot 
Am I supposed to share my gemini api key also or leave blank space for it and just share the code ?

**Comment by itsmohit097** [comment]
@KhushiTiwarii join discord and tage me , we will discuss there.

**Comment by KhushiTiwarii** [comment]
hi @itsmohit097 I have raised a pr
I have kept API_KEY='' you have to replace it with your gemini api key.
I have created a pull request from my forked frontend branch to your frontend branch 
Kindly check
