### ISSUE TITLE
[ENHANCEMENT STYLING]: New UI for whole frontend

### ISSUE THREAD

**Issue by itsmohit097** [itsmohit097/medi-hub#60]
## Description

You have to create only a new UI design for the whole front end. 
You don't have to do the coding part.
## Reference Design
[https://www.figma.com/file/5yGqKh1YI5ugGXuUK721XV/Aprycot-Lite-%E2%80%93-Free-Restaurant-Admin-Dashboard-Template-(Community)?type=design&node-id=2-646&mode=design&t=6yOj4A5M56bQefvG-0
https://www.figma.com/file/NxgCKYZVVQvTtKshCzRPYe/Medical-Dashboard-(Community)?type=design&node-id=0-1&mode=design&t=OE7QuiWYm8T2vrwt-0](https://www.figma.com/file/5yGqKh1YI5ugGXuUK721XV/Aprycot-Lite-%E2%80%93-Free-Restaurant-Admin-Dashboard-Template-(Community)?type=design&node-id=2-646&mode=design&t=mi7FRlQDmlJV4Mtv-0)

## Reference Colors
![original-2f4fb18b0995dddfb7f505200438084a](https://github.com/itsmohit097/medi-hub/assets/125040386/0505abfd-83d9-4d94-a5ae-a0d2f7cd960e)

## NOTE 
I will be working with you on this issue.
Need to complete work in total 7 days and at least landing page in 2-3 days

**Comment by MitulSonagara** [comment]
I can help you with this... 
and i have one suggestion for you in your main page of website the carousal speed is very high and this makes the overall performance of website very low so please fix that..

**Comment by Harshitazz** [comment]
i can do this.

**Comment by shanvi2001** [comment]
I can do this

**Comment by itsmohit097** [comment]
@MitulSonagara @Harshitazz @shanvi2001 pls share some of ur work?

**Comment by MitulSonagara** [comment]
https://github.com/itsmohit097/medi-hub/assets/95460188/f1a93635-cc51-4210-931b-da986d008950

https://github.com/itsmohit097/medi-hub/assets/95460188/28107af0-2d3d-4aeb-bc68-67f98117fd02

**Comment by shanvi2001** [comment]
https://www.linkedin.com/posts/shanvi-kumari-484198267_octanetservices-octanet-octanetinternship-activity-7183551326667116544-RbQq?utm_source=share&utm_medium=member_android

**Comment by itsmohit097** [comment]
Added by me
