### ISSUE TITLE
[ENHANCEMENT FUNCTION] : ZOD validation

### ISSUE THREAD

**Issue by sum1t-here** [itsmohit097/medi-hub#63]
## Description

Zod is a TypeScript-first schema declaration and validation library. I'm using the term "schema" to broadly refer to any data type, from a simple string to a complex nested object.

Zod is designed to be as developer-friendly as possible. The goal is to eliminate duplicative type declarations. With Zod, you declare a validator once and Zod will automatically infer the static TypeScript type. It's easy to compose simpler types into complex data structures.

[More about zod](https://zod.dev/?id=introduction)

## Actual Behavior

In backend controllers, before implementing Zod, your code relies on manual checks to ensure that the required fields are present in the request body and that an admin with the provided email doesn't already exist in the database. While this approach is functional, it lacks the benefits of type safety and declarative validation that Zod provides.

## Expected Behavior

With Zod, you can define a schema for the request body, specifying the expected shape and data types of the input fields. This not only ensures type safety but also simplifies validation logic by centralizing it within the schema definition.

## Steps to Reproduce (if applicable)

1. Step 1
2. Step 2
3. Step 3

## Screenshots (if applicable)

Actual:
(screenshot)

Expected (highlight the part that requires changes):
Entire backend controllers

**Comment by sum1t-here** [comment]
hey @itsmohit097 assign me this issue under GSSOC'24

**Comment by itsmohit097** [comment]
@sum1t-here 
once all major features come into work you can start working on this till then wait
if I forget tag me on Discord: https://discord.gg/krQd2Fss

**Comment by sum1t-here** [comment]
Ok

**Comment by Manaswini123456** [comment]
@sum1t-here Kindly assign this issue to me. As a full stack developer, I have the comprehensive knowledge and expertise required to handle it effectively.

**Comment by itsmohit097** [comment]
dont need zod validation now
