### ISSUE TITLE
It is 2024. Update Your Footer.

### ISSUE THREAD

**Issue by kashhisshh** [itsmohit097/medi-hub#64]
Change your static timestamp to an automatically updating copyright year or other dynamic timestamp.

**Comment by kapilG0** [comment]
Hello @itsmohit097 please assign this issue to me

**Comment by itsmohit097** [comment]
> Change your static timestamp to an automatically updating copyright year or other dynamic timestamp.

@kashhisshh  assigned to u
Fork the repo correctly.(Read contribution.md)

**Comment by kapilG0** [comment]
Hello @kashhisshh I tried to rectify that issue by fork that repo and checked the code I think it is already implemented I mean year is coming dynamically so is it required to add time stamp as well in that ?

**Comment by kashhisshh** [comment]
ya with the new UI its fixed now

**Comment by kapilG0** [comment]
> ya with the new UI its fixed now

Ok so I think this needs to be closed
