### ISSUE TITLE
[BUG] Links in the navbar and footer are not correct

### ISSUE THREAD

**Issue by Sibam-Paul** [itsmohit097/medi-hub#65]
## Description
The discord icon and github icon in the navbar and footer;
and the insta icon in the footer 

## Actual Behavior
**in the nav bar:-**
the dicord icon is not redirect to discord rather than old github page
the Github icon is redirecting to old page

**In the footer**
No links are working

## Expected Behavior
All links should be redirected to correct pages

## Screenshots
```
Expected (highlight the part that requires changes):
(screenshot)
```
In the navbar
![image](https://github.com/itsmohit097/medi-hub/assets/158052549/07a4e3ea-39c8-457a-82a3-099c98d56a62)

In the footer
![image](https://github.com/itsmohit097/medi-hub/assets/158052549/7c5e5a9c-b2bb-4da2-a378-e40b1e2757aa)

**Please assign me this issue under GSSOC'24** 
`Please give important tags to this issue and mention level 1`

please provide contact info as I want to ask u a thing for instagram ID 
or should I remove it ??

**Comment by itsmohit097** [comment]
already done.
