### ISSUE TITLE
[BUG]: Change Twitter logo to X

### ISSUE THREAD

**Issue by prachi-kurmi** [itsmohit097/medi-hub#68]
## Description
![Screenshot (79)](https://github.com/itsmohit097/medi-hub/assets/125259987/24624557-25ae-4ead-ad22-e254f9f3567d)

As seen in the screenshot, the twitter logo needs to be updated with X logo. Please assign this issue to me under Gssoc24.

Select program in which you are contributing
GSSoC24

**Comment by adarshjagati07** [comment]
hey, assign me this issue from gssoc'24.

**Comment by itsmohit097** [comment]
@prachi-kurmi assigned to u.
Important: Do the fork and branch process properly (read contribution.md file)
if not followed properly PR will not be merged
