### ISSUE TITLE
[BUG/FEAT] Login and Signup buttons are not working.

### ISSUE THREAD

**Issue by SaurabhS55** [itsmohit097/medi-hub#69]
Hey @itsmohit097, I've checked out your website, and I must say, it's impressive! I appreciate the effort you've put into it. However, I've noticed a couple of bugs or missing features, such as the login and signup buttons not functioning properly. Upon clicking these buttons, the login and signup pages fail to display.

Screenshots:
![image](https://github.com/itsmohit097/medi-hub/assets/119050714/dfcc285d-f28d-453b-8f36-c46594add0b2)

I'd like to propose adding the following features:
1. Login and Signup page with React form validation.
2. Feature of "Login with Google" using Oauth or passport.js library.

These enhancements will greatly improve the intuitiveness and user-friendliness of the login and signup functionalities.

I would like to work on this issue. could you assign this issue to me with GSSOC'24 label.

**Comment by itsmohit097** [comment]
already done by someone else
