### ISSUE TITLE
[FEAT] : Adding login/signup pages

### ISSUE THREAD

**Issue by nagalakshmi08** [itsmohit097/medi-hub#7]
![Screenshot 2024-05-10 202729](https://github.com/itsmohit097/medi-hub/assets/121669832/88b03522-1ee0-4305-83bc-3c1917d89bb8)

I would like to add login/signup pages for the user authentication. Kindly assign me this task I can fix this issue.

**Comment by itsmohit097** [comment]
@nagalakshmi08  assign this issue to you.
Kindly read the README.md and CONTRIBUTING.md file before the contribution.
I'll add the gssoc label later for now you can start working on it.

**Comment by gayathrik23** [comment]
@itsmohit097  can you assign this issue to me under Gssoc'24

**Comment by Tushar7436** [comment]
@itsmohit097  I would love to solve this issue, please assign me this issue.

**Comment by Hardikchandra** [comment]
@itsmohit097 I can work on the authentication part ,required in LOGIN and SIGNUP pages allow user to succesfully. #7
