### ISSUE TITLE
Adding respective icons to the navbar

### ISSUE THREAD

**Issue by harshmishra19** [itsmohit097/medi-hub#76]
## Description

Please provide a brief description of the issue or feature request.

## Actual Behavior

Please describe what actually happened.

The current navbar lacks icons, which impacts its visual appeal and usability. Users might find it less engaging and intuitive to navigate through the website without visual cues provided by icons.

## Expected Behavior

Please describe what you expected to happen.

## Steps to Reproduce (if applicable)

I propose adding respective icons to the navbar to enhance its visual appeal and improve user navigation experience. These icons will align with the theme of the website and provide users with clear visual cues for each navigation option

1. Step 1
2. Step 2
3. Step 3

## Screenshots (if applicable)

Actual:
(screenshot)
![Screenshot 2024-05-13 103808](https://github.com/itsmohit097/medi-hub/assets/115486960/e12b128f-4df3-4523-9a0e-0bb21dc2ec8f)

Expected (highlight the part that requires changes):
(screenshot)

![Screenshot 2024-05-11 080754](https://github.com/itsmohit097/medi-hub/assets/115486960/a151e0bc-587c-4d0f-b280-5e5c4eaedfea)
![Screenshot 2024-05-12 083752](https://github.com/itsmohit097/medi-hub/assets/115486960/30ade5fa-e002-4aa9-ab1f-27ec8b3b8bcc)

**Comment by Kshitij2027** [comment]
I want to solve this issue... Please assign me

**Comment by Kshitij2027** [comment]
I would be happy to clear this issue. Assign me this issue please.

**Comment by adarshjagati07** [comment]
Hey, I want to solve this issue under GSSOC'24. Please assign the issue to me.

**Comment by itsmohit097** [comment]
i stick to current navbar
