### ISSUE TITLE
[FEAT] Adding sign up backend and frontend functionality for the existing app

### ISSUE THREAD

**Issue by amit429** [itsmohit097/medi-hub#79]
## Description

I would like to take up the task of adding the sign up Functionality frontend and backend.
I am a GSSOC'24 contributor and would like to add sign up to this project.

## Actual Behavior
Right now when we click on sign up button in the navbar we route to that page but nothing shows up

## Expected Behavior
It should show a form which takes all the user details and registers them to the website and redirects them to the login page after registration.

## Screenshots (if applicable)

Actual:
![image](https://github.com/itsmohit097/medi-hub/assets/68067897/7b9c2b77-db10-4fb6-8a78-ba0a2a0a1fad)

Expected (highlight the part that requires changes):
![image](https://github.com/itsmohit097/medi-hub/assets/68067897/4f7a657b-ca57-4602-80f6-725f9ab3b318)

**Comment by amit429** [comment]
@itsmohit097 please assign this task for me under the GSSOC'24 tag

**Comment by amit429** [comment]
@itsmohit097 can you please assign this

**Comment by itsmohit097** [comment]
Already done by someone else
