### ISSUE TITLE
[Enhancement]: Improving footer section style and adding functionality

### ISSUE THREAD

**Issue by nagalakshmi08** [itsmohit097/medi-hub#8]
![Screenshot 2024-05-10 203118](https://github.com/itsmohit097/medi-hub/assets/121669832/34aa4233-e396-49a3-8c6d-6e16b3c5a2a4)

Hi @itsmohit097 , The footer will look good if it has full width instead of white spaces at left and right. Also the links are not clickable, they are not being redirected to any page. Kindly assign me this task I want to contribute to this project and I will fix this issue.

**Comment by Sumkaur02** [comment]
Kindly assign this task to me. I want to contribute to this project under Gssoc'24.

**Comment by itsmohit097** [comment]
I'll assign this issue to both @nagalakshmi08 @Sumkaur02 
Kindly read the README.md and CONTRIBUTING.md file before the contribution.
I'll add the gssoc label later you both can start working on it.

**Comment by itsmohit097** [comment]
Sorry,@Sumkaur02  there is a rule I wasn't aware of: only one person will be assigned to one issue.
if @nagalakshmi08 will not be interested in this issue or can not do it in a limited time. I will assign it to you.

**Comment by nagalakshmi08** [comment]
Thank you for clarifying the rule @itsmohit097, I am interested in handling this issue.
