### ISSUE TITLE
Add appointment type , method and duration in the backend

### ISSUE THREAD

**Issue by Mohitgit22** [itsmohit097/medi-hub#80]
##Description

I'm adding new fields to the backend schema of the appointment management system using Mongoose and MongoDB .

## Actual Behavior

The backend schema currently lacks fields for Appointment Type, Appointment Duration, and Booking Method.

##Expected Behavior

I expect to add these new fields to enhance the functionality of the appointment management system.

Changes in backend

Appointment Type: Appointments can now be categorized as regular check-up, emergency, consultation, etc.
Appointment Duration: Appointment duration can now be scheduled according to the preference of the user.
Booking Method: A field indicating the booking source (online, phone, in-person) has been added for appointments.

**Comment by Mohitgit22** [comment]
@itsmohit097  please assign this task for me under the GSSOC'24 tag.

**Comment by itsmohit097** [comment]
@Mohitgit22 we have written backend for appointment .
In appointment form there is only data showing from the patient and doctor's model.
We will not taking any input from the user.
If any functionality u want to add on this existed functionality. Kindly suggest here
