### ISSUE TITLE
[FEAT/ENHANCEMENT STYLING/ENHANCEMENT FUNCTION] Complete All doctors page 

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [itsmohit097/medi-hub#81]
I would like to work on all doctors page.

The idea is first it will ask the section like below.

![Screenshot_20240513_125106_Chrome](https://github.com/itsmohit097/medi-hub/assets/139672976/77283c4f-67d5-40ef-b054-2d4bf212a100)

Then according to the type it will sort listed the do tors details as below.

![Screenshot_20240513_125128_Chrome](https://github.com/itsmohit097/medi-hub/assets/139672976/9fa4c383-745f-408a-8b2e-29b031d23415)

I can add more details of each doctor and give a direct link to appointment. So it will directly redirect to appointment page.

Please assign this issue to me under gssoc24. I AM REALLY VERY interested to work in this project. If you have any suggestions on my idea, please tell me. I can do it.

**Comment by DharshiBalasubramaniyam** [comment]
@itsmohit097 please check this issue

**Comment by itsmohit097** [comment]
@DharshiBalasubramaniyam someone working on the doctors page 
I want a search functionality on this page.
Exactly like this (all inputs will be in one row)
https://www.apollo247.com/specialties

**Comment by DharshiBalasubramaniyam** [comment]
Hi @itsmohit097, Do i need to do only the below section with cities filter or entire page?

![image](https://github.com/itsmohit097/medi-hub/assets/139672976/86a84878-eb8c-4914-994b-308a60a5ec8a)

**Comment by itsmohit097** [comment]
@DharshiBalasubramaniyam  you only need to add these three filter options
![Screenshot_2024_0522_223037](https://github.com/itsmohit097/medi-hub/assets/125040386/bb0b72f9-2168-4842-8bcd-c7f6cf0a97ba)

**Comment by DharshiBalasubramaniyam** [comment]
Got it. I can do it @itsmohit097.

**Comment by itsmohit097** [comment]
@DharshiBalasubramaniyam do u want to work on this issue (create search functionality only frontend part) ??
