### ISSUE TITLE
[Fix]: Creating a navbar fixed at top 

### ISSUE THREAD

**Issue by itsmohit097** [itsmohit097/medi-hub#83]
## Description

Changing the ui of current Navabr.

## Screenshots (if applicable)

Actual:
![old_navbar](https://github.com/itsmohit097/medi-hub/assets/125040386/b1f61171-94dd-4676-b1de-6756577125fe)

Expected (highlight the part that requires changes):
(screenshot)
![navbar](https://github.com/itsmohit097/medi-hub/assets/125040386/ca9c8718-37ca-4766-86c6-636653a1f7fb)
Keep the socials same as previous one and make it position: fixed

**Comment by shreyvarshney1** [comment]
@itsmohit097 I would like to contribute to this. Please Assign me this issue.

**Comment by Hardikchandra** [comment]
@itsmohit097 I want to work on the enhancement styling part of the navbar as you described in the issue #83

**Comment by shreyvarshney1** [comment]
I have kept the previous socials as the same and made the navbar fixed position. Please review it and merge my pull request #89 . Looking forward to contribute more.

**Comment by TusharKumar0907** [comment]
I also want to work on it Please assign it to me under GSSOC24 label
