### ISSUE TITLE
[ENHANCEMENT STYLING]: Creating New Hero Section

### ISSUE THREAD

**Issue by itsmohit097** [itsmohit097/medi-hub#84]
## Description

Change the old hero section.

Actual:
![Screenshot (292)](https://github.com/itsmohit097/medi-hub/assets/125040386/4fa99940-db35-4fa5-b50c-6943547b246d)

Expected (highlight the part that requires changes):
![new hero](https://github.com/itsmohit097/medi-hub/assets/125040386/9c97c8a6-75c1-43fe-8144-d9b814707096)
keep the boxes empty for now if you any idea add something (hint: icon with suitable text)
png added named as: (new_hero)
colors added named as: (main_theme, light_theme)

**Comment by DharshiBalasubramaniyam** [comment]
I am like to work in this issue.
Can you please assign me under GSSOC'24?

**Comment by AlaynaShaheen** [comment]
Hello @itsmohit097 ,

I am Alayna Shaheen, a contributor participating in GSSoC'24. I want to work on this feature. Please assign this issue to me. I'm eager to tackle this challenge and contribute to the project. Looking forward on your guidance on how to proceed.

Regards,
Alayna Shaheen

**Comment by itsmohit097** [comment]
@AlaynaShaheen can you complete this wkrk by today

**Comment by AlaynaShaheen** [comment]
Yes I can complete it by today @itsmohit097

**Comment by itsmohit097** [comment]
@AlaynaShaheen assigned to you.
do the fork and switch branch process properly (read contributon.md)
if not followed properly PR will not be merged

**Comment by AlaynaShaheen** [comment]
Ok. Thank for assigning this to me @itsmohit097

**Comment by AlaynaShaheen** [comment]
@itsmohit097 Is it ok if I redirect  user to home page whenever he clicks on MEDIHUB logo as there is no HOME option in new UI design. Also which page should to be linked to MEDICINES?
![Screenshot 2024-05-15 105838](https://github.com/itsmohit097/medi-hub/assets/111679498/e22ed6bc-ba84-4e4d-a535-fc80442f0017)

**Comment by itsmohit097** [comment]
@AlaynaShaheen  link the homepage to the logo leave the medicine function 
Keep the socials as in the old ui.

**Comment by AlaynaShaheen** [comment]
Also should I leave the carousel as it is or remove carousel and add this image as static one?
![Screenshot 2024-05-15 131712](https://github.com/itsmohit097/medi-hub/assets/111679498/6f78eed8-43b6-4d6c-aeb3-b5862679c1e7)

**Comment by AlaynaShaheen** [comment]
Ok

**Comment by AlaynaShaheen** [comment]
@itsmohit097 I am getting an error that deployment has failed.
![Screenshot 2024-05-15 212517](https://github.com/itsmohit097/medi-hub/assets/111679498/64159b7a-2ead-4646-a2f6-0a0369fc398e)

**Comment by AlaynaShaheen** [comment]
@itsmohit097 I have solved the issue and created a pull request #118 .Kindly review the PR and let me know if there are any changes to be made further.
