### ISSUE TITLE
[FEAT] Added a  back to Top  button 

### ISSUE THREAD

**Issue by Arghyadeep09** [itsmohit097/medi-hub#87]
## Problem : 
The absence of a back-to-top button on the website significantly impairs its user-friendliness and navigational convenience, posing a notable problem in terms of user experience

## Actual Behavior

The Back to top button is not present 

## Expected Behavior

There should be a back to top button 

## Steps to Reproduce (if applicable)

1. Step1 : Open the website 
2. Step 2 : Scroll to the bottom of the page

## Screenshots (if applicable)

Actual:
(screenshot)
![image](https://github.com/itsmohit097/medi-hub/assets/90449806/b17fa51d-6d0c-481a-9e38-21fe9f6e4974)

Expected (highlight the part that requires changes):
(screenshot)
![image](https://github.com/itsmohit097/medi-hub/assets/90449806/6c26f9a5-3665-4674-9667-4646f37b3bb6)

##Video

https://github.com/itsmohit097/medi-hub/assets/90449806/8abb5ce4-51d6-43cb-a2a8-1959178d77de

**Comment by Arghyadeep09** [comment]
Under GSSOC 24, Please assign the work to me!

**Comment by itsmohit097** [comment]
@Arghyadeep09 assigned to you.
Kindly read the contribution.md file , if not followed properly PR will not be merged.
Do the fork and switch branch process correctly.

**Comment by Arghyadeep09** [comment]
when i am trying to push it is saying permission denied why?

![image](https://github.com/itsmohit097/medi-hub/assets/90449806/9035409c-73bc-4713-a87f-9fb4afc88ccd)

**Comment by Arghyadeep09** [comment]
@itsmohit097 Why this message is showing when i am trying to push?

![image](https://github.com/itsmohit097/medi-hub/assets/90449806/38aadce4-89f2-4aba-aea0-5fae1c573bc4)
