### ISSUE TITLE
[Enhancement UI]: Adding a FAQ section

### ISSUE THREAD

**Issue by Hardikchandra** [itsmohit097/medi-hub#88]
@itsmohit097 , ADDING FAq SECTION TO ANSWER QUESTION REALTED TO MEDI-HUB. IS A GREATE FEATURE THAT CAN BE ADDDED ON.

**Comment by itsmohit097** [comment]
@Hardikchandra assigned to you.
kindly read the contribution.md file, iff not followed properly PR will not be merged.
Do the fork and branch process correctly.

**Comment by itsmohit097** [comment]
@Hardikchandra sorry for the late response.
i checked this is not a duplicate issue.
do u want to work on this issue?

**Comment by Hardikchandra** [comment]
@itsmohit097 , Yes.

**Comment by itsmohit097** [comment]
@Hardikchandra assigned
Important: Do the fork and branch process properly (read contribution.md file)
if not followed properly PR will not be merged

**Comment by itsmohit097** [comment]
@Hardikchandra update??

**Comment by itsmohit097** [comment]
@Hardikchandra 
Today is the deadline for submitting a PR for this issue. I will close it tomorrow.

**Comment by Hardikchandra** [comment]
> @Hardikchandra 
> Today is the deadline for submitting a PR for this issue. If you are unable to complete it by today, it will be assigned to someone else.
> you can take ref from here https://www.apollo247.com/doctors/dr-tripti-deb-1c92b055-80aa-4872-a239-71f523055436?source=Listing_Page see at the bottom of the page

Yes, sure I will create a PR by tonight. Sorry for the delay.

**Comment by Hardikchandra** [comment]
> @Hardikchandra 
> Today is the deadline for submitting a PR for this issue. If you are unable to complete it by today, it will be assigned to someone else.
> you can take ref from here https://www.apollo247.com/doctors/dr-tripti-deb-1c92b055-80aa-4872-a239-71f523055436?source=Listing_Page see at the bottom of the page

@itsmohit097 , I have successfully created the PR request.
