### ISSUE TITLE
[FEAT]: Adding carousel in hero section

### ISSUE THREAD

**Issue by Harshitazz** [itsmohit097/medi-hub#9]
**carousel enhance the overall appeal of the site.**
![Screenshot 2024-05-10 204724](https://github.com/itsmohit097/medi-hub/assets/118474653/07d76708-6997-400c-a143-53676409b51d)
will be done by importing react lib-> slick

**Comment by itsmohit097** [comment]
> **carousel enhance the overall appeal of the site.** ![Screenshot 2024-05-10 204724](https://private-user-images.githubusercontent.com/118474653/329630258-07d76708-6997-400c-a143-53676409b51d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzODAwODYsIm5iZiI6MTcxNTM3OTc4NiwicGF0aCI6Ii8xMTg0NzQ2NTMvMzI5NjMwMjU4LTA3ZDc2NzA4LTY5OTctNDAwYy1hMTQzLTUzNjc2NDA5YjUxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQyMjIzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmVjODQ4NTBmMDEzZmNmNzVkNmIyNjhmN2EyYzhhMTI1ZmY5NWJiNTI1ZGYxZmU0MWMxOWIwYTEyZWE1MTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Fi7AAcjw79X8kjyEZZ4IWAevkf2z_yPT5o1kWXysGa0) will be done by importing react lib-> slick

@Harshitazz assigned this issue to you.
i have already install react-carousel lib (if not comfortable with this no problem go ahead with your choice)
Make sure only image will slide not the text and button. 
Try to find good images to match this theme(if not found no issue).
Kindly read the README.md and CONTRIBUTING.md file before the contribution.
I'll add the gssoc label later for now you can start working on it.

**Comment by Harshitazz** [comment]
![h](https://github.com/itsmohit097/medi-hub/assets/118474653/52dd3a50-fc5c-42e1-8ebb-45038342736c)
ig its an issue with ip address.
