### ISSUE TITLE
[BUG]-Transition speed is pretty fast

### ISSUE THREAD

**Issue by Scrapper700** [itsmohit097/medi-hub#90]
## Description

I'm looking for assistance in slowing down the transition between slides on my website, which utilizes the Slick slider plugin.

## Actual Behavior
Currently, the transition between slides happens too rapidly, causing a less-than-ideal user experience.

## Expected Behavior
I would like to reduce the speed of transitioning between slides to ensure a smoother and more controlled browsing experience for my visitors.

## Steps to Reproduce 
Visit the website.
Observe the quick transition between slides.
Notice the rapid pace at which the slides change.

Before:
https://github.com/itsmohit097/medi-hub/assets/113296663/84b7309b-9005-4ec3-b33b-f9105f01789c

After:

https://github.com/itsmohit097/medi-hub/assets/113296663/610df3b8-1824-4db3-b8ff-5af606291c43

**Comment by Scrapper700** [comment]
@itsmohit097 please assign me this task under GSSOC'24

**Comment by Scrapper700** [comment]
@itsmohit097 ??

**Comment by itsmohit097** [comment]
hero section is changed now
