### ISSUE TITLE
[FEAT]: Adding GitHub Automatic Greeting Bot

### ISSUE THREAD

**Issue by Hemu21** [itsmohit097/medi-hub#93]
## Description

Currently This repo does not have greeting bot. As it is a open source so many people create the issues. There is No one to greet the issue creator. GitHub greeting Bot will automatically greet them when they create a issue

## Actual Behavior

Currently This repo does not have greeting bot. As it is a open source so many people create the issues. There is No one to greet the issue creator. GitHub bot is not added.

## Expected Behavior

Currently This repo does not have greeting bot. As it is a open source so many people create the issues. GitHub greeting Bot will automatically greet them when they create a issue. I will add github bot.

## Steps to Reproduce (if applicable)

1.  please check the issues.

**Comment by Hemu21** [comment]
@itsmohit097 can you please assign me this issue.

**Comment by itsmohit097** [comment]
@Hemu21 assigned
Important: Do the fork and branch process properly (read contribution.md file)
if not followed properly PR will not be merged
