### ISSUE TITLE
[ENHANCEMENT STYLING]: Centering text on Navbar and improving its look.

### ISSUE THREAD

**Issue by chhavx1618** [itsmohit097/medi-hub#97]
## Description

The Navbar text is uncentered, more on the lower side. Also, the sign up button is escaping the navbar. It's length is not fitting entirely.

## Actual Behavior

Text in the navbar is not in the centered, giving slight imperfection in the look. The bottom part of the sign up button is outside the Navbar.

## Expected Behavior

The text in the navbar should be in the exact center of the bar. The sign up button should have the same height as that of the navbar.

## Screenshots 

To be changed: 
![image](https://github.com/itsmohit097/medi-hub/assets/152146397/80b0377f-e6df-408a-b459-98b2b24df16a)

**Comment by chhavx1618** [comment]
I would like to work on this issue under GSSoC'24. Please assign me this issue.

**Comment by itsmohit097** [comment]
already done
