### ISSUE TITLE
[Enhancement Styling]: Adding a contributors section on homepage

### ISSUE THREAD

**Issue by sharmi4590** [itsmohit097/medi-hub#98]
Hey @itsmohit097 
## Description

Please provide a brief description of the issue or feature request.
I will add testimonials to your website which are usually present above the footer which is a must and should for the best user experience .In the Talented team section some cards seem to be missing I will make it as an automatic slider which will run on a loop and show all the doctors image even in smaller dimensions, It will look more working website.

## Steps to Reproduce (if applicable)

1. Step 1 Add testimonials 
![Screenshot (383)](https://github.com/itsmohit097/medi-hub/assets/102676949/754b88b7-d9f5-45fa-a08c-937661ef3f11)
This is my previous work.
2. Step 2 I can add automatic slider to the talented team it only stops when someone puts the cursor on it.
![Screenshot (384)](https://github.com/itsmohit097/medi-hub/assets/102676949/83fe54fa-fb5c-4c5e-8bda-cd4ada6ccd1e)
This is my previous work.

## Screenshots (if applicable)
![Screenshot (381)](https://github.com/itsmohit097/medi-hub/assets/102676949/64d8b53f-d911-4de1-bcf1-209725c23b94)
Only two members are visible in smaller dimensions.

**Comment by itsmohit097** [comment]
@sharmi4590 i want to replace this section with "our contributions section"
https://www.figma.com/design/eZiyFxl7zkLx9hE0Uz10zb/Untitled?node-id=1-14&t=Oq7OC61x2vartG1Y-1
want to work on this ??

**Comment by sharmi4590** [comment]
@itsmohit097 Yes I would like to work on it.

**Comment by itsmohit097** [comment]
@sharmi4590 assigned to u.
[Important] : 
Do not waste your precious time. Kindly do the fork and branch process properly (read contribution.md file)
If not followed properly PR will not be merged and the issue will be assigned to another contributor.

**Comment by itsmohit097** [comment]
@sharmi4590 update??

**Comment by sharmi4590** [comment]
@itsmohit097 Yes it will be done by today.
