### ISSUE TITLE
UI Improvisation of Book your appointment now

### ISSUE THREAD

**Issue by riya-rjha** [itsmohit097/medi-hub#99]
The button of Book your appointment now in the main section has a UI that is being overlapped by the background image of the main section. This leads to lesser visibility of text & the button. I would want to change the UI of the button. Please assign this issue to me under the gssoc label. 

Here's what needs to be changed: 

![Screenshot (568)](https://github.com/itsmohit097/medi-hub/assets/112813772/2d4bcf6a-1ddb-4b63-a6ad-7d7b46ecf5be)

**Comment by itsmohit097** [comment]
hero section is already changed
